export type VisualFamily =
  | 'bar-column'
  | 'combo'
  | 'line-area'
  | 'composition'
  | 'relationship'
  | 'tabular'
  | 'card-kpi'
  | 'slicer'
  | 'advanced'

export type VisualKind =
  | 'bar'
  | 'column'
  | 'combo'
  | 'line'
  | 'area'
  | 'composition'
  | 'relationship'
  | 'table'
  | 'matrix'
  | 'card'
  | 'kpi'
  | 'slicer'
  | 'tree'

export type VisualCoverageStatus = 'full' | 'partial' | 'none' | 'planned' | 'needs-review'
export type VisualImplementationStatus = 'implemented' | 'partial' | 'planned' | 'needs-review'

export interface VisualCatalogEntry {
  id: string
  displayName: string
  family: VisualFamily
  visualKind: VisualKind
  title: string
  subtitle: string
  previewComponentId: string | null
  currentAliases?: string[]
  existsInSelector: boolean
  formatSchema: VisualCoverageStatus
  livePreviewBinding: VisualCoverageStatus
  jsonExportMapping: VisualCoverageStatus
  implementationStatus: VisualImplementationStatus
  powerBiVisualStyleKeys?: string[]
  notes?: string
}

export const VISUAL_CATALOG = [
  {
    id: 'bar',
    displayName: 'Bar Chart',
    family: 'bar-column',
    visualKind: 'bar',
    title: 'Sales by Category',
    subtitle: 'Bar Chart',
    previewComponentId: 'bar',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['barChart'],
    notes: 'Uses the Batch 1 Bar / Stacked Bar schema even though the planned catalog starts with stacked bar.',
  },
  {
    id: 'stackedbar',
    displayName: 'Stacked Bar Chart',
    family: 'bar-column',
    visualKind: 'bar',
    title: 'Category Mix by Region',
    subtitle: 'Stacked Bar Chart',
    previewComponentId: 'stackedbar',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['barChart'],
  },
  {
    id: 'clusteredbar',
    displayName: 'Clustered Bar Chart',
    family: 'bar-column',
    visualKind: 'bar',
    title: 'Team Performance',
    subtitle: 'Clustered Bar Chart',
    previewComponentId: 'clusteredbar',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['clusteredBarChart'],
  },
  {
    id: 'hundredstackedbar',
    displayName: '100% Stacked Bar Chart',
    family: 'bar-column',
    visualKind: 'bar',
    title: 'Market Share by Region',
    subtitle: '100% Stacked Bar Chart',
    previewComponentId: 'hundredstackedbar',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['hundredPercentStackedBarChart'],
  },
  {
    id: 'column',
    displayName: 'Column Chart',
    family: 'bar-column',
    visualKind: 'column',
    title: 'Budget vs Actual',
    subtitle: 'Column Chart',
    previewComponentId: 'column',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['columnChart'],
    notes: 'Uses the Batch 1 Column / Stacked Column schema.',
  },
  {
    id: 'stackedcol',
    displayName: 'Stacked Column Chart',
    family: 'bar-column',
    visualKind: 'column',
    title: 'Regional Sales Mix',
    subtitle: 'Stacked Column Chart',
    previewComponentId: 'stackedcol',
    currentAliases: ['stackedcolumn'],
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['columnChart'],
  },
  {
    id: 'clusteredcol',
    displayName: 'Clustered Column Chart',
    family: 'bar-column',
    visualKind: 'column',
    title: 'Regional Comparison',
    subtitle: 'Clustered Column Chart',
    previewComponentId: 'clusteredcol',
    currentAliases: ['clusteredcolumn'],
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['clusteredColumnChart'],
  },
  {
    id: 'hundredstackedcol',
    displayName: '100% Stacked Column Chart',
    family: 'bar-column',
    visualKind: 'column',
    title: 'Segment Contribution',
    subtitle: '100% Stacked Column Chart',
    previewComponentId: 'hundredstackedcol',
    currentAliases: ['hundredstackedcolumn'],
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['hundredPercentStackedColumnChart'],
  },
  {
    id: 'lineclustered',
    displayName: 'Line and Clustered Column Chart',
    family: 'combo',
    visualKind: 'combo',
    title: 'Revenue and Units Sold',
    subtitle: 'Line & Clustered Column',
    previewComponentId: 'lineclustered',
    currentAliases: ['lineclusteredcolumn'],
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['lineClusteredColumnComboChart'],
  },
  {
    id: 'linestacked',
    displayName: 'Line and Stacked Column Chart',
    family: 'combo',
    visualKind: 'combo',
    title: 'Sales Mix and Growth',
    subtitle: 'Line & Stacked Column',
    previewComponentId: 'linestacked',
    currentAliases: ['linestackedcolumn'],
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['lineStackedColumnComboChart'],
  },
  {
    id: 'line',
    displayName: 'Line Chart',
    family: 'line-area',
    visualKind: 'line',
    title: 'Revenue Trend',
    subtitle: 'Line Chart',
    previewComponentId: 'line',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['lineChart'],
  },
  {
    id: 'area',
    displayName: 'Area Chart',
    family: 'line-area',
    visualKind: 'area',
    title: 'Growth Trend',
    subtitle: 'Area Chart',
    previewComponentId: 'area',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['areaChart'],
  },
  {
    id: 'stackedarea',
    displayName: 'Stacked Area Chart',
    family: 'line-area',
    visualKind: 'area',
    title: 'Cumulative Sales',
    subtitle: 'Stacked Area Chart',
    previewComponentId: 'stackedarea',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['areaChart'],
  },
  {
    id: 'hundredstackedarea',
    displayName: '100% Stacked Area Chart',
    family: 'line-area',
    visualKind: 'area',
    title: '100% Stacked Area',
    subtitle: '100% Stacked Area Chart',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
  },
  {
    id: 'pie',
    displayName: 'Pie Chart',
    family: 'composition',
    visualKind: 'composition',
    title: 'Market Share',
    subtitle: 'Pie Chart',
    previewComponentId: 'pie',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['pieChart'],
  },
  {
    id: 'donut',
    displayName: 'Donut Chart',
    family: 'composition',
    visualKind: 'composition',
    title: 'Revenue by Category',
    subtitle: 'Donut Chart',
    previewComponentId: 'donut',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['donutChart'],
  },
  {
    id: 'funnel',
    displayName: 'Funnel Chart',
    family: 'composition',
    visualKind: 'composition',
    title: 'Sales Funnel',
    subtitle: 'Funnel Chart',
    previewComponentId: 'funnel',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['funnel'],
  },
  {
    id: 'treemap',
    displayName: 'Treemap',
    family: 'composition',
    visualKind: 'composition',
    title: 'Product Performance',
    subtitle: 'Treemap',
    previewComponentId: 'treemap',
    existsInSelector: true,
    formatSchema: 'partial',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['treemap'],
  },
  {
    id: 'waterfall',
    displayName: 'Waterfall Chart',
    family: 'composition',
    visualKind: 'composition',
    title: 'P&L Breakdown',
    subtitle: 'Waterfall Chart',
    previewComponentId: 'waterfall',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['waterfallChart'],
  },
  {
    id: 'ribbon',
    displayName: 'Ribbon Chart',
    family: 'composition',
    visualKind: 'composition',
    title: 'Category Rank over Time',
    subtitle: 'Ribbon Chart',
    previewComponentId: 'ribbon',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['ribbonChart'],
  },
  {
    id: 'scatter',
    displayName: 'Scatter Chart',
    family: 'relationship',
    visualKind: 'relationship',
    title: 'Revenue vs Profit',
    subtitle: 'Scatter Chart',
    previewComponentId: 'scatter',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['scatterChart'],
  },
  {
    id: 'bubble',
    displayName: 'Bubble Chart',
    family: 'relationship',
    visualKind: 'relationship',
    title: 'Revenue vs Margin',
    subtitle: 'Bubble Chart',
    previewComponentId: 'bubble',
    currentAliases: ['scatterBubblePreview'],
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'partial',
    jsonExportMapping: 'none',
    implementationStatus: 'partial',
    notes: 'Rendered separately from scatter; no dedicated Power BI visualStyles key is emitted yet.',
  },
  {
    id: 'table',
    displayName: 'Table',
    family: 'tabular',
    visualKind: 'table',
    title: 'Sales Summary',
    subtitle: 'Table',
    previewComponentId: 'table',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['tableEx'],
  },
  {
    id: 'matrix',
    displayName: 'Matrix',
    family: 'tabular',
    visualKind: 'matrix',
    title: 'Regional Performance',
    subtitle: 'Matrix',
    previewComponentId: 'matrix',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'partial',
    implementationStatus: 'partial',
    powerBiVisualStyleKeys: ['pivotTable'],
  },
  {
    id: 'cardCurrent',
    displayName: 'Card (new)',
    family: 'card-kpi',
    visualKind: 'card',
    title: 'Current Card',
    subtitle: 'Card (new)',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'partial',
    implementationStatus: 'planned',
    powerBiVisualStyleKeys: ['card'],
  },
  {
    id: 'cardLegacy',
    displayName: 'Card (legacy)',
    family: 'card-kpi',
    visualKind: 'card',
    title: 'Legacy Card',
    subtitle: 'Card (legacy)',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
  },
  {
    id: 'multirowcard',
    displayName: 'Multi-row Card',
    family: 'card-kpi',
    visualKind: 'card',
    title: 'Multi-row Card',
    subtitle: 'Multi-row Card',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
  },
  {
    id: 'kpi',
    displayName: 'KPI',
    family: 'card-kpi',
    visualKind: 'kpi',
    title: 'KPI',
    subtitle: 'KPI',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
    notes: 'Dashboard KPI strip exists, but KPI is not a selectable chart visual yet.',
  },
  {
    id: 'slicerStandard',
    displayName: 'Slicer',
    family: 'slicer',
    visualKind: 'slicer',
    title: 'Slicer',
    subtitle: 'Standard Slicer',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
    notes: 'Dashboard slicer zones exist, but slicers are not selectable visuals yet.',
  },
  {
    id: 'buttonSlicer',
    displayName: 'Button Slicer',
    family: 'slicer',
    visualKind: 'slicer',
    title: 'Button Slicer',
    subtitle: 'Button Slicer',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
  },
  {
    id: 'listSlicer',
    displayName: 'List Slicer',
    family: 'slicer',
    visualKind: 'slicer',
    title: 'List Slicer',
    subtitle: 'List Slicer',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
  },
  {
    id: 'tileSlicer',
    displayName: 'Tile Slicer',
    family: 'slicer',
    visualKind: 'slicer',
    title: 'Tile Slicer',
    subtitle: 'Tile Slicer',
    previewComponentId: null,
    existsInSelector: false,
    formatSchema: 'none',
    livePreviewBinding: 'planned',
    jsonExportMapping: 'planned',
    implementationStatus: 'planned',
  },
  {
    id: 'decompositiontree',
    displayName: 'Decomposition Tree',
    family: 'advanced',
    visualKind: 'tree',
    title: 'Revenue Drivers',
    subtitle: 'Decomposition Tree',
    previewComponentId: 'decompositiontree',
    existsInSelector: true,
    formatSchema: 'none',
    livePreviewBinding: 'none',
    jsonExportMapping: 'none',
    implementationStatus: 'partial',
  },
] as const satisfies readonly VisualCatalogEntry[]

export const SELECTOR_VISUAL_CATALOG = VISUAL_CATALOG.filter((visual) => visual.existsInSelector)

export const VISUAL_CATALOG_IDS = VISUAL_CATALOG.map((visual) => visual.id)
export const SELECTOR_VISUAL_IDS = SELECTOR_VISUAL_CATALOG.map((visual) => visual.id)
