// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const ANALYTICS_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-bar-chart",
    "name": "Bar Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "chart",
      "graph",
      "bars",
      "report",
      "visual",
      "bar",
      "analytics"
    ],
    "aliases": [],
    "description": "Bar Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"11\" width=\"3.4\" height=\"9\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"10.3\" y=\"6\" width=\"3.4\" height=\"14\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"16.6\" y=\"3\" width=\"3.4\" height=\"17\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"11\" width=\"3.4\" height=\"9\" rx=\"1\" fill=\"#868E96\"/><rect x=\"10.3\" y=\"6\" width=\"3.4\" height=\"14\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"16.6\" y=\"3\" width=\"3.4\" height=\"17\" rx=\"1\" fill=\"#0CA678\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-line-chart",
    "name": "Line Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "trend",
      "graph",
      "report",
      "visual",
      "analytics",
      "line",
      "chart"
    ],
    "aliases": [],
    "description": "Line Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 18.5 9 12.5 13 15.5 20.5 6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9\" cy=\"12.5\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"13\" cy=\"15.5\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"20.5\" cy=\"6\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 18.5 9 12.5 13 15.5 20.5 6\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"9\" cy=\"12.5\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"13\" cy=\"15.5\" r=\"1.2\" fill=\"#F08C00\"/><circle cx=\"20.5\" cy=\"6\" r=\"1.2\" fill=\"#0CA678\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-pie-chart",
    "name": "Pie Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "report",
      "breakdown",
      "share",
      "visual",
      "analytics",
      "pie",
      "chart"
    ],
    "aliases": [],
    "description": "Pie Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3.5a8.5 8.5 0 1 0 8.5 8.5H12Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5V12h8.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3.5a8.5 8.5 0 1 0 8.5 8.5H12Z\" fill=\"#4C6EF5\" fill-opacity=\"0.18\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 3.5V12h8.5\" fill=\"#0CA678\" fill-opacity=\"0.25\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-donut-chart",
    "name": "Donut Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "report",
      "breakdown",
      "ring",
      "visual",
      "analytics",
      "donut",
      "chart"
    ],
    "aliases": [],
    "description": "Donut Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"3.6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 4a8 8 0 0 1 6.9 12\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"3.6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\"/><path d=\"M12 4a8 8 0 0 1 6.9 12\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"2.2\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-scatter-chart",
    "name": "Scatter Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "correlation",
      "plot",
      "points",
      "visual",
      "analytics",
      "scatter",
      "chart"
    ],
    "aliases": [
      "Scatter Plot"
    ],
    "description": "Scatter Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 3.5v17h17\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"15\" r=\"1.2\" fill=\"currentColor\"/><circle cx=\"12.5\" cy=\"10\" r=\"1.2\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"14\" r=\"1.2\" fill=\"currentColor\"/><circle cx=\"19\" cy=\"7.5\" r=\"1.2\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 3.5v17h17\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"8\" cy=\"15\" r=\"1.3\" fill=\"#4C6EF5\"/><circle cx=\"12.5\" cy=\"10\" r=\"1.3\" fill=\"#0CA678\"/><circle cx=\"16\" cy=\"14\" r=\"1.3\" fill=\"#F08C00\"/><circle cx=\"19\" cy=\"7.5\" r=\"1.3\" fill=\"#E03131\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-dashboard",
    "name": "Dashboard",
    "primaryCategory": "analytics",
    "keywords": [
      "report",
      "overview",
      "panel",
      "visual",
      "analytics",
      "dashboard"
    ],
    "aliases": [
      "Dashboard Grid"
    ],
    "description": "Dashboard — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"3.5\" width=\"18\" height=\"17\" rx=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 9.5h18\" stroke=\"currentColor\"/><path d=\"M9.5 9.5v11\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"3.5\" width=\"18\" height=\"17\" rx=\"2.2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M3 9.5h18\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M9.5 9.5v11\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><rect x=\"4.4\" y=\"5\" width=\"5.6\" height=\"4\" rx=\"0.8\" fill=\"#4C6EF5\" fill-opacity=\"0.25\"/><rect x=\"11\" y=\"11\" width=\"8.6\" height=\"3\" rx=\"0.8\" fill=\"#0CA678\" fill-opacity=\"0.3\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-table",
    "name": "Data Table",
    "primaryCategory": "analytics",
    "keywords": [
      "report",
      "grid",
      "rows",
      "columns",
      "visual",
      "table",
      "data",
      "analytics"
    ],
    "aliases": [],
    "description": "Data Table — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 9.5h17M3.5 14.5h17M9.5 4.5v15M15.5 4.5v15\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"1.8\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\"/><path d=\"M3.5 9.5h17M3.5 14.5h17M9.5 4.5v15M15.5 4.5v15\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-filter",
    "name": "Filter",
    "primaryCategory": "analytics",
    "keywords": [
      "slicer",
      "drill",
      "segment",
      "query",
      "visual",
      "filter",
      "analytics"
    ],
    "aliases": [
      "Data Filter"
    ],
    "description": "Filter — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 5h16l-6 7.5v6L10 21v-8.5Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 5h16l-6 7.5v6L10 21v-8.5Z\" fill=\"#4C6EF5\" fill-opacity=\"0.22\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-drill-down",
    "name": "Drill Down",
    "primaryCategory": "analytics",
    "keywords": [
      "expand",
      "detail",
      "explore",
      "visual",
      "report",
      "drill",
      "down",
      "analytics"
    ],
    "aliases": [
      "Data Insight"
    ],
    "description": "Drill Down — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"7\" rx=\"1.4\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"13\" width=\"7\" height=\"7\" rx=\"1.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 11 13 13\" stroke=\"currentColor\"/><path d=\"M16.2 15.8 18.2 17.8M18.2 15.8v2h-2\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"7\" rx=\"1.4\" fill=\"#868E96\" fill-opacity=\"0.2\" stroke=\"#868E96\" stroke-width=\"1.6\"/><rect x=\"13\" y=\"13\" width=\"7\" height=\"7\" rx=\"1.4\" fill=\"#4C6EF5\" fill-opacity=\"0.22\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M11 11 13 13\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-refresh",
    "name": "Refresh Data",
    "primaryCategory": "analytics",
    "keywords": [
      "reload",
      "sync",
      "update",
      "query",
      "report",
      "refresh",
      "data",
      "analytics"
    ],
    "aliases": [],
    "description": "Refresh Data — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4.5 12a7.5 7.5 0 0 1 12.6-5.5M19.5 12a7.5 7.5 0 0 1-12.6 5.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 3.5v3.5h-3.5M7 20.5V17h3.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4.5 12a7.5 7.5 0 0 1 12.6-5.5M19.5 12a7.5 7.5 0 0 1-12.6 5.5\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M17 3.5v3.5h-3.5M7 20.5V17h3.5\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-export",
    "name": "Export",
    "primaryCategory": "analytics",
    "keywords": [
      "download",
      "save",
      "share",
      "report",
      "data",
      "export",
      "analytics"
    ],
    "aliases": [],
    "description": "Export — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3v12\" stroke=\"currentColor\"/><path d=\"M7.5 9.5 12 5l4.5 4.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4.5 16v3a1.5 1.5 0 0 0 1.5 1.5h12a1.5 1.5 0 0 0 1.5-1.5v-3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3v12\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M7.5 9.5 12 5l4.5 4.5\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4.5 16v3a1.5 1.5 0 0 0 1.5 1.5h12a1.5 1.5 0 0 0 1.5-1.5v-3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-bookmark-report",
    "name": "Report Bookmark",
    "primaryCategory": "analytics",
    "keywords": [
      "save",
      "state",
      "view",
      "marker",
      "report",
      "bookmark",
      "analytics"
    ],
    "aliases": [],
    "description": "Report Bookmark — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 3.5h12v17l-6-4-6 4Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 3.5h12v17l-6-4-6 4Z\" fill=\"#F5A623\" fill-opacity=\"0.25\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-forecast",
    "name": "Forecast",
    "primaryCategory": "analytics",
    "keywords": [
      "prediction",
      "projection",
      "trend",
      "future",
      "forecast",
      "analytics"
    ],
    "aliases": [
      "Forecast Trend"
    ],
    "description": "Forecast — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 17 8 12 12 14.5 16 8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 8 20.5 4.5M20.5 4.5v3.5M20.5 4.5h-3.5\" fill=\"none\" stroke=\"currentColor\" stroke-dasharray=\"2.6 2.2\"/>",
    "multicolorSvg": "<path d=\"M3.5 17 8 12 12 14.5 16 8\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 8 20.5 4.5\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-dasharray=\"2.6 2.2\"/><path d=\"M20.5 4.5v3.5M20.5 4.5h-3.5\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-target",
    "name": "Target / Goal",
    "primaryCategory": "kpi",
    "keywords": [
      "goal",
      "kpi",
      "objective",
      "performance",
      "target"
    ],
    "aliases": [],
    "description": "Target / Goal — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"4.4\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"4.4\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"1.3\" fill=\"#E03131\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-trend-up",
    "name": "Trend Up",
    "primaryCategory": "kpi",
    "keywords": [
      "growth",
      "increase",
      "positive",
      "performance",
      "trend",
      "up",
      "kpi"
    ],
    "aliases": [
      "Trending Up"
    ],
    "description": "Trend Up — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 16 9.5 10 13.5 13.5 20.5 6.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M20.5 6.5h-4.4M20.5 6.5v4.4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 16 9.5 10 13.5 13.5 20.5 6.5\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20.5 6.5h-4.4M20.5 6.5v4.4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-trend-down",
    "name": "Trend Down",
    "primaryCategory": "kpi",
    "keywords": [
      "decline",
      "decrease",
      "negative",
      "performance",
      "trend",
      "down",
      "kpi"
    ],
    "aliases": [],
    "description": "Trend Down — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 8 9.5 14 13.5 10.5 20.5 17.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M20.5 17.5h-4.4M20.5 17.5v-4.4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 8 9.5 14 13.5 10.5 20.5 17.5\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20.5 17.5h-4.4M20.5 17.5v-4.4\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-scorecard",
    "name": "Scorecard",
    "primaryCategory": "kpi",
    "keywords": [
      "rating",
      "performance",
      "review",
      "summary",
      "scorecard",
      "kpi"
    ],
    "aliases": [],
    "description": "Scorecard — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"3.5\" width=\"16\" height=\"17\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9.5h8M8 13h8M8 16.5h5\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"3.5\" width=\"16\" height=\"17\" rx=\"2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M8 9.5h8\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M8 13h8\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M8 16.5h5\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-benchmark",
    "name": "Benchmark",
    "primaryCategory": "kpi",
    "keywords": [
      "comparison",
      "standard",
      "performance",
      "reference",
      "benchmark",
      "kpi"
    ],
    "aliases": [],
    "description": "Benchmark — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 20V9M4 9 8 5l4 4 4-4 4 4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M2.5 20h19\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 20V9M4 9 8 5l4 4 4-4 4 4\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M2.5 20h19\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-milestone",
    "name": "Milestone",
    "primaryCategory": "kpi",
    "keywords": [
      "achievement",
      "checkpoint",
      "progress",
      "project",
      "milestone",
      "kpi"
    ],
    "aliases": [],
    "description": "Milestone — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 3v18\" stroke=\"currentColor\"/><path d=\"M6 4.5h11l-3 3.5 3 3.5H6Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 3v18\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M6 4.5h11l-3 3.5 3 3.5H6Z\" fill=\"#E03131\" fill-opacity=\"0.22\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-rating-star",
    "name": "Rating / Star",
    "primaryCategory": "kpi",
    "keywords": [
      "review",
      "quality",
      "score",
      "star",
      "rating",
      "kpi"
    ],
    "aliases": [],
    "description": "Rating / Star — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3.7 14.4 9 20 9.8 16 13.8 17 19.4 12 16.7 7 19.4 8 13.8 4 9.8 9.6 9Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3.7 14.4 9 20 9.8 16 13.8 17 19.4 12 16.7 7 19.4 8 13.8 4 9.8 9.6 9Z\" fill=\"#F5A623\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-percentage",
    "name": "Percentage",
    "primaryCategory": "kpi",
    "keywords": [
      "rate",
      "ratio",
      "share",
      "kpi",
      "metric",
      "percentage"
    ],
    "aliases": [],
    "description": "Percentage — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"7\" r=\"2.6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"17\" r=\"2.6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 6 6 18\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"7\" r=\"2.6\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"17\" r=\"2.6\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M18 6 6 18\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-growth",
    "name": "Growth",
    "primaryCategory": "kpi",
    "keywords": [
      "increase",
      "expand",
      "performance",
      "plant",
      "scale",
      "growth",
      "kpi"
    ],
    "aliases": [],
    "description": "Growth — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 21V11\" stroke=\"currentColor\"/><path d=\"M12 11C12 7 9 6 6 6c0 3.5 2.4 5.5 6 5Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 14c0-3.6 2.6-5 5.5-5.2-.2 3.2-2.2 5.4-5.5 5.2Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 21V11\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M12 11C12 7 9 6 6 6c0 3.5 2.4 5.5 6 5Z\" fill=\"#0CA678\" fill-opacity=\"0.3\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 14c0-3.6 2.6-5 5.5-5.2-.2 3.2-2.2 5.4-5.5 5.2Z\" fill=\"#0CA678\" fill-opacity=\"0.45\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-area-chart",
    "name": "Area Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "trend",
      "filled",
      "region",
      "report",
      "area",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Area Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 18.5 8 13 12 15 16 9.5 20.5 13\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 18.5V20.5H20.5V13\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 18.5 8 13 12 15 16 9.5 20.5 13V20.5H3.5Z\" fill=\"currentColor\" fill-opacity=\"0.12\" stroke=\"none\"/>",
    "multicolorSvg": "<path d=\"M3.5 18.5 8 13 12 15 16 9.5 20.5 13V20.5H3.5Z\" fill=\"#4C6EF5\" fill-opacity=\"0.18\"/><path d=\"M3.5 18.5 8 13 12 15 16 9.5 20.5 13\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-bubble-chart",
    "name": "Bubble Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "bubbles",
      "size",
      "distribution",
      "bubble",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Bubble Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9\" cy=\"14\" r=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"14.5\" cy=\"10\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"16\" r=\"1.4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"9\" cy=\"14\" r=\"2.2\" fill=\"#4C6EF5\" fill-opacity=\"0.5\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"14.5\" cy=\"10\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.5\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"16\" r=\"1.4\" fill=\"#F08C00\" fill-opacity=\"0.6\" stroke=\"#F08C00\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-radar-chart",
    "name": "Radar Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "spider",
      "polar",
      "multivariate",
      "radar",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Radar Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 19 8 16.5 17 7.5 17 5 8Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7 15.5 9.5 14 14.5 10 14.5 8.5 9.5Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"3\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"19\" cy=\"8\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"5\" cy=\"8\" r=\"0.9\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3 19 8 16.5 17 7.5 17 5 8Z\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 7 15.5 9.5 14 14.5 10 14.5 8.5 9.5Z\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.3\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-funnel-chart",
    "name": "Funnel Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "conversion",
      "stages",
      "pipeline",
      "funnel",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Funnel Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 5H20L15 12V19L9 16V12Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 5H20L15 12V19L9 16V12Z\" fill=\"#4C6EF5\" fill-opacity=\"0.18\"/><path d=\"M4 5H20L15 12V19L9 16V12Z\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-gauge-chart",
    "name": "Gauge Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "speedometer",
      "kpi",
      "meter",
      "gauge",
      "chart",
      "analytics"
    ],
    "aliases": [
      "Gauge / Score",
      "Gauge",
      "Speed Gauge",
      "KPI Gauge"
    ],
    "description": "Gauge Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 16a8 8 0 0 1 16 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 16 16 10\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"16\" r=\"1.3\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 16a8 8 0 0 1 16 0\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 16 16 10\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"16\" r=\"1.4\" fill=\"#2B2D42\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-heatmap",
    "name": "Heatmap",
    "primaryCategory": "analytics",
    "keywords": [
      "grid",
      "density",
      "matrix",
      "heatmap",
      "analytics"
    ],
    "aliases": [],
    "description": "Heatmap — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 9.3H20M4 14.6H20M9.3 4V20M14.6 4V20\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.85\"/><rect x=\"9.3\" y=\"4\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.6\"/><rect x=\"14.6\" y=\"4\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#E03131\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"9.3\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.5\"/><rect x=\"9.3\" y=\"9.3\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#E03131\" fill-opacity=\"0.7\"/><rect x=\"14.6\" y=\"9.3\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.5\"/><rect x=\"4\" y=\"14.6\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#E03131\" fill-opacity=\"0.6\"/><rect x=\"9.3\" y=\"14.6\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.7\"/><rect x=\"14.6\" y=\"14.6\" width=\"5.3\" height=\"5.3\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.8\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-treemap",
    "name": "Treemap",
    "primaryCategory": "analytics",
    "keywords": [
      "hierarchy",
      "blocks",
      "proportion",
      "treemap",
      "analytics"
    ],
    "aliases": [],
    "description": "Treemap — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M13 4V13M4 13H20M13 8.5H20\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"9\" height=\"9\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"4.5\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.8\"/><rect x=\"13\" y=\"8.5\" width=\"7\" height=\"4.5\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.8\"/><rect x=\"4\" y=\"13\" width=\"16\" height=\"7\" rx=\"1\" fill=\"#7048E8\" fill-opacity=\"0.8\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-waterfall-chart",
    "name": "Waterfall Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "bridge",
      "cumulative",
      "variance",
      "waterfall",
      "chart",
      "analytics"
    ],
    "aliases": [
      "Waterfall 2",
      "Waterfall2"
    ],
    "description": "Waterfall Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"5.5\" y=\"8\" width=\"2.5\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"9\" y=\"6\" width=\"2.5\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"12.5\" y=\"10\" width=\"2.5\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"16\" y=\"7\" width=\"2.5\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"5.5\" y=\"8\" width=\"2.5\" height=\"4\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"9\" y=\"6\" width=\"2.5\" height=\"4\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"12.5\" y=\"10\" width=\"2.5\" height=\"6\" rx=\"1\" fill=\"#E03131\"/><rect x=\"16\" y=\"7\" width=\"2.5\" height=\"5\" rx=\"1\" fill=\"#4C6EF5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-candlestick",
    "name": "Candlestick Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "ohlc",
      "stock",
      "finance",
      "trading",
      "candlestick",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Candlestick Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M7 4V20M15 4V20\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"5.2\" y=\"8\" width=\"3.6\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13.2\" y=\"7\" width=\"3.6\" height=\"8\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M7 4V20M15 4V20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"5.2\" y=\"8\" width=\"3.6\" height=\"6\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"13.2\" y=\"7\" width=\"3.6\" height=\"8\" rx=\"1\" fill=\"#E03131\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-sankey",
    "name": "Sankey Diagram",
    "primaryCategory": "analytics",
    "keywords": [
      "flow",
      "links",
      "nodes",
      "sankey",
      "diagram",
      "analytics"
    ],
    "aliases": [],
    "description": "Sankey Diagram — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"5\" width=\"2.5\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"3\" y=\"13\" width=\"2.5\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"18.5\" y=\"8\" width=\"2.5\" height=\"8\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5.5 7.5C12 7.5 12 12 18.5 12\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5.5 15.5C12 15.5 12 13 18.5 13\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"5\" width=\"2.5\" height=\"5\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"3\" y=\"13\" width=\"2.5\" height=\"5\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"18.5\" y=\"8\" width=\"2.5\" height=\"8\" rx=\"1\" fill=\"#7048E8\"/><path d=\"M5.5 7.5C12 7.5 12 12 18.5 12\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5.5 15.5C12 15.5 12 13 18.5 13\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-histogram",
    "name": "Histogram",
    "primaryCategory": "analytics",
    "keywords": [
      "distribution",
      "frequency",
      "bars",
      "histogram",
      "analytics"
    ],
    "aliases": [],
    "description": "Histogram — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"5\" y=\"14\" width=\"2.4\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"7.6\" y=\"10\" width=\"2.4\" height=\"8\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"10.2\" y=\"7\" width=\"2.4\" height=\"11\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"12.8\" y=\"11\" width=\"2.4\" height=\"7\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"15.4\" y=\"15\" width=\"2.4\" height=\"3\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"5\" y=\"14\" width=\"2.4\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.6\"/><rect x=\"7.6\" y=\"10\" width=\"2.4\" height=\"8\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.75\"/><rect x=\"10.2\" y=\"7\" width=\"2.4\" height=\"11\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"12.8\" y=\"11\" width=\"2.4\" height=\"7\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.75\"/><rect x=\"15.4\" y=\"15\" width=\"2.4\" height=\"3\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-pivot-table",
    "name": "Pivot Table",
    "primaryCategory": "analytics",
    "keywords": [
      "crosstab",
      "matrix",
      "summarize",
      "pivot",
      "table",
      "analytics"
    ],
    "aliases": [],
    "description": "Pivot Table — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 9H20M9 4V20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11.5 11.5H18M11.5 14.5H18M11.5 17.5H18\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"5\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"9\" width=\"5\" height=\"11\" rx=\"1\" fill=\"#7048E8\" fill-opacity=\"0.18\"/><path d=\"M4 9H20M9 4V20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-kpi-card",
    "name": "KPI Card",
    "primaryCategory": "kpi",
    "keywords": [
      "metric",
      "tile",
      "scorecard",
      "kpi",
      "card"
    ],
    "aliases": [],
    "description": "KPI Card — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 9H13\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 13H17\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 16.5H11\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.1\"/><rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 9H13\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 13H17\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 16.5H11\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-column-chart",
    "name": "Column Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "vertical",
      "bars",
      "grouped",
      "compare",
      "column",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Column Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"8\" width=\"3.5\" height=\"12\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8.5\" y=\"5\" width=\"3.5\" height=\"15\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"10\" width=\"3.5\" height=\"10\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"17.5\" y=\"3\" width=\"3.5\" height=\"17\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"8\" width=\"3.5\" height=\"12\" rx=\"1\" fill=\"#868E96\"/><rect x=\"8.5\" y=\"5\" width=\"3.5\" height=\"15\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"13\" y=\"10\" width=\"3.5\" height=\"10\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"17.5\" y=\"3\" width=\"3.5\" height=\"17\" rx=\"1\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-grouped-bar",
    "name": "Grouped Bar Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "compare",
      "multi",
      "series",
      "clusters",
      "grouped",
      "bar",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Grouped Bar Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"6\" width=\"3\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8\" y=\"6\" width=\"3\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"4\" y=\"12\" width=\"3\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8\" y=\"12\" width=\"3\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"4\" y=\"20\" width=\"3\" height=\"2\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8\" y=\"20\" width=\"3\" height=\"2\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"6\" width=\"3\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"8\" y=\"6\" width=\"3\" height=\"4\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"4\" y=\"12\" width=\"3\" height=\"6\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"8\" y=\"12\" width=\"3\" height=\"6\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"4\" y=\"20\" width=\"3\" height=\"2\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"8\" y=\"20\" width=\"3\" height=\"2\" rx=\"1\" fill=\"#0CA678\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-stacked-bar",
    "name": "Stacked Bar Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "stacked",
      "cumulative",
      "segments",
      "bar",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Stacked Bar Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 14H20M4 10H20\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"4\" rx=\"1.5\" fill=\"#4C6EF5\"/><rect x=\"4\" y=\"8\" width=\"16\" height=\"4\" rx=\"1.5\" fill=\"#0CA678\"/><rect x=\"4\" y=\"12\" width=\"16\" height=\"4\" rx=\"1.5\" fill=\"#F08C00\"/><rect x=\"4\" y=\"16\" width=\"16\" height=\"4\" rx=\"1.5\" fill=\"#868E96\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-combo-chart",
    "name": "Combo Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "bar",
      "line",
      "mixed",
      "dual",
      "axis",
      "combo",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Combo Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"10\" width=\"2.5\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"10\" y=\"7\" width=\"2.5\" height=\"9\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13.5\" y=\"12\" width=\"2.5\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 13 9 9 13 11 19 7\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"#1C7ED6\" fill-opacity=\"0.08\"/><rect x=\"6\" y=\"10\" width=\"2.5\" height=\"6\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"10\" y=\"7\" width=\"2.5\" height=\"9\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"13.5\" y=\"12\" width=\"2.5\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\"/><path d=\"M5 13 9 9 13 11 19 7\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-slope-chart",
    "name": "Slope Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "before",
      "after",
      "change",
      "connect",
      "slope",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Slope Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 7 17 13M7 13 17 8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"7\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"7\" cy=\"13\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"17\" cy=\"13\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"17\" cy=\"8\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 7 17 13\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 13 17 8\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-dot-plot",
    "name": "Dot Plot",
    "primaryCategory": "analytics",
    "keywords": [
      "distribution",
      "points",
      "axis",
      "cleveland",
      "dot",
      "plot",
      "analytics"
    ],
    "aliases": [],
    "description": "Dot Plot — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"16\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"10\" cy=\"11\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"14\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"14\" cy=\"8\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"12\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"18\" cy=\"9\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"8\" cy=\"16\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"10\" cy=\"11\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"12\" cy=\"14\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"8\" r=\"1.2\" fill=\"#F08C00\"/><circle cx=\"16\" cy=\"12\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"18\" cy=\"9\" r=\"1.2\" fill=\"#4C6EF5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-box-plot",
    "name": "Box Plot",
    "primaryCategory": "analytics",
    "keywords": [
      "whisker",
      "quartile",
      "outlier",
      "stats",
      "box",
      "plot",
      "analytics"
    ],
    "aliases": [],
    "description": "Box Plot — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M8 5V19M16 5V19\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8\" y=\"8\" width=\"8\" height=\"8\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12h8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 7h6M5 17h6M13 6h6M13 18h6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M8 5V19M16 5V19\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"8\" y=\"8\" width=\"8\" height=\"8\" rx=\"0.5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\"/><rect x=\"8\" y=\"8\" width=\"8\" height=\"8\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 12h8\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-pareto",
    "name": "Pareto Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "80",
      "20",
      "rule",
      "cumulative",
      "line",
      "pareto",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Pareto Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"5\" y=\"10\" width=\"3\" height=\"10\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"9.5\" y=\"7\" width=\"3\" height=\"13\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"14\" width=\"3\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"18.5\" y=\"17\" width=\"2\" height=\"3\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 9 11 7.5 15 13 20 16.5\" fill=\"none\" stroke=\"#E03131\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"5\" y=\"10\" width=\"3\" height=\"10\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"9.5\" y=\"7\" width=\"3\" height=\"13\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><rect x=\"14\" y=\"14\" width=\"3\" height=\"6\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.6\"/><rect x=\"18.5\" y=\"17\" width=\"2\" height=\"3\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.4\"/><path d=\"M5 9 11 7.5 15 13 20 16.5\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-matrix",
    "name": "Matrix Chart",
    "primaryCategory": "analytics",
    "keywords": [
      "quadrant",
      "2x2",
      "bcg",
      "positioning",
      "matrix",
      "chart",
      "analytics"
    ],
    "aliases": [],
    "description": "Matrix Chart — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H20M12 4V20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"7\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"7\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"8\" cy=\"15\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"14\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"11\" cy=\"10\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.15\"/><rect x=\"12\" y=\"4\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"4\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.15\"/><rect x=\"12\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#868E96\" fill-opacity=\"0.15\"/><circle cx=\"16\" cy=\"7\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"7\" cy=\"7\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"15\" cy=\"14\" r=\"1.5\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-drill-through",
    "name": "Drill Through",
    "primaryCategory": "analytics",
    "keywords": [
      "navigate",
      "detail",
      "click",
      "cross",
      "drill",
      "through",
      "analytics"
    ],
    "aliases": [],
    "description": "Drill Through — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"10\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 15v5M9 20h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9.5 8.5l2.5 2 2.5-2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 4l3 3-3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"10\" r=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 15v5M9 20h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9.5 8.5l2.5 2 2.5-2\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 4l3 3-3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-cross-filter",
    "name": "Cross Filter",
    "primaryCategory": "analytics",
    "keywords": [
      "highlight",
      "interact",
      "linked",
      "selection",
      "cross",
      "filter",
      "analytics"
    ],
    "aliases": [],
    "description": "Cross Filter — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"5\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"5\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 12h2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 9h2M6 12h2M6 15h2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 9h2M16 12h2M16 15h2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"5\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"13\" y=\"5\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"#0CA678\" fill-opacity=\"0.15\"/><rect x=\"3\" y=\"5\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"13\" y=\"5\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M11 12h2\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-tooltip",
    "name": "Tooltip",
    "primaryCategory": "analytics",
    "keywords": [
      "hover",
      "detail",
      "popup",
      "label",
      "tooltip",
      "analytics"
    ],
    "aliases": [],
    "description": "Tooltip — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 14l2 3 2-3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 8h10M7 11h7\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"10\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.12\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M10 14l2 3 2-3\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 8h10M7 11h7\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-slicer",
    "name": "Slicer",
    "primaryCategory": "analytics",
    "keywords": [
      "filter",
      "control",
      "slice",
      "power",
      "bi",
      "slicer",
      "analytics"
    ],
    "aliases": [],
    "description": "Slicer — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"4\" y=\"11\" width=\"16\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"4\" y=\"18\" width=\"16\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"6\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"8\" cy=\"13\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"8\" cy=\"20\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"11\" width=\"16\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"4\" y=\"18\" width=\"16\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"8\" cy=\"6\" r=\"1.2\" fill=\"#fff\"/><circle cx=\"8\" cy=\"13\" r=\"1.2\" fill=\"#868E96\"/><circle cx=\"8\" cy=\"20\" r=\"1.2\" fill=\"#868E96\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-anomaly",
    "name": "Anomaly Detection",
    "primaryCategory": "analytics",
    "keywords": [
      "outlier",
      "spike",
      "unusual",
      "alert",
      "anomaly",
      "detection",
      "analytics"
    ],
    "aliases": [],
    "description": "Anomaly Detection — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 14 7 12 10 15 13 8 16 16 19 7\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"19\" cy=\"7\" r=\"2.5\" fill=\"#E03131\" fill-opacity=\"0.2\" stroke=\"#E03131\"/>",
    "multicolorSvg": "<path d=\"M3 14 7 12 10 15 13 8 16 16 19 7\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"19\" cy=\"7\" r=\"2.5\" fill=\"#E03131\" fill-opacity=\"0.2\" stroke=\"#E03131\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-cagr",
    "name": "CAGR",
    "primaryCategory": "kpi",
    "keywords": [
      "compound",
      "annual",
      "growth",
      "rate",
      "trend",
      "cagr",
      "kpi"
    ],
    "aliases": [
      "Compound Growth"
    ],
    "description": "CAGR — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 18 8 12 12 14 16 8 20 10\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 18H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M20 6l-4 4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 18 8 12 12 14 16 8 20 10\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 18H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20 6l-4 4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ytd",
    "name": "YTD",
    "primaryCategory": "kpi",
    "keywords": [
      "year",
      "to",
      "date",
      "cumulative",
      "period",
      "progress",
      "ytd",
      "kpi"
    ],
    "aliases": [],
    "description": "YTD — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H14V20H4Z\" fill=\"#4C6EF5\" fill-opacity=\"0.4\" stroke=\"none\"/><path d=\"M14 12H20V20h-6Z\" fill=\"#868E96\" fill-opacity=\"0.15\" stroke=\"none\"/><path d=\"M7 7h10\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"8\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 7h10\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-mom-growth",
    "name": "MoM Growth",
    "primaryCategory": "kpi",
    "keywords": [
      "month",
      "over",
      "compare",
      "change",
      "mom",
      "growth",
      "kpi"
    ],
    "aliases": [],
    "description": "MoM Growth — professional KPI and performance tracking icon for Power BI dashboards.",
    "recommendedUses": [
      "KPI cards",
      "Scorecards",
      "Conditional formatting icons"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 10h7v10H4Z\" fill=\"#4C6EF5\" fill-opacity=\"0.5\" stroke=\"none\"/><path d=\"M13 7h7v13h-7Z\" fill=\"#0CA678\" fill-opacity=\"0.5\" stroke=\"none\"/><rect x=\"4\" y=\"4\" width=\"7\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"16\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"16\" rx=\"1.5\" fill=\"#0CA678\" fill-opacity=\"0.8\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-dax-measure",
    "name": "DAX Measure",
    "primaryCategory": "analytics",
    "keywords": [
      "formula",
      "calculate",
      "power",
      "bi",
      "expression",
      "dax",
      "measure",
      "analytics"
    ],
    "aliases": [],
    "description": "DAX Measure — professional analytics and reporting icon for Power BI dashboards.",
    "recommendedUses": [
      "Report visuals and headers",
      "Bookmark navigation",
      "Visual titles"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9h2M8 12h2M14 9h2M14 12h2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 9v3h4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 9h2M8 12h2M14 9h2M14 12h2\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 9v3h4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-growth-arrow-up",
    "name": "Growth (Increase)",
    "primaryCategory": "variance",
    "keywords": [
      "growth",
      "arrow",
      "up",
      "increase",
      "variance"
    ],
    "aliases": [],
    "description": "Growth (Increase) — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"4\" y1=\"20\" x2=\"4\" y2=\"9\"/><line x1=\"4\" y1=\"9\" x2=\"1\" y2=\"12\"/><line x1=\"4\" y1=\"9\" x2=\"7\" y2=\"12\"/><path d=\"M9 20V13a3 3 0 0 1 6 0v7\"/><path d=\"M18 20V6a3 3 0 0 1 3 0\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-decline-arrow-down",
    "name": "Decline (Decrease)",
    "primaryCategory": "variance",
    "keywords": [
      "decline",
      "arrow",
      "down",
      "decrease",
      "variance"
    ],
    "aliases": [],
    "description": "Decline (Decrease) — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"4\" y1=\"4\" x2=\"4\" y2=\"15\"/><line x1=\"4\" y1=\"15\" x2=\"1\" y2=\"12\"/><line x1=\"4\" y1=\"15\" x2=\"7\" y2=\"12\"/><path d=\"M9 4v11a3 3 0 0 0 6 0V4\"/><path d=\"M18 4v14a3 3 0 0 1-3 3\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-increase-caret",
    "name": "Increase",
    "primaryCategory": "variance",
    "keywords": [
      "increase",
      "caret",
      "variance"
    ],
    "aliases": [],
    "description": "Increase — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"9.4\"/><polyline points=\"7.5,13.8 12,9 16.5,13.8\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-decrease-caret",
    "name": "Decrease",
    "primaryCategory": "variance",
    "keywords": [
      "decrease",
      "caret",
      "variance"
    ],
    "aliases": [],
    "description": "Decrease — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"9.4\"/><polyline points=\"7.5,10.2 12,15 16.5,10.2\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-percent-change",
    "name": "Percent Change",
    "primaryCategory": "variance",
    "keywords": [
      "percent",
      "change",
      "variance"
    ],
    "aliases": [],
    "description": "Percent Change — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"5\" y1=\"19\" x2=\"19\" y2=\"5\"/><circle cx=\"7.5\" cy=\"7.5\" r=\"2.3\"/><circle cx=\"16.5\" cy=\"16.5\" r=\"2.3\"/><line x1=\"17\" y1=\"4\" x2=\"20\" y2=\"4\"/><line x1=\"18.5\" y1=\"2.5\" x2=\"18.5\" y2=\"5.5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-margin-layers",
    "name": "Margin",
    "primaryCategory": "variance",
    "keywords": [
      "margin",
      "layers",
      "variance"
    ],
    "aliases": [],
    "description": "Margin — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"3\" width=\"16\" height=\"18\" rx=\"1.5\"/><line x1=\"4\" y1=\"9\" x2=\"20\" y2=\"9\"/><line x1=\"4\" y1=\"15\" x2=\"20\" y2=\"15\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-gross-margin-wedge",
    "name": "Gross Margin",
    "primaryCategory": "variance",
    "keywords": [
      "gross",
      "margin",
      "wedge",
      "variance"
    ],
    "aliases": [],
    "description": "Gross Margin — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"9.4\"/><path d=\"M12 12V2.6A9.4 9.4 0 0 1 20 17.3Z\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-target-growth",
    "name": "Growth Target",
    "primaryCategory": "variance",
    "keywords": [
      "target",
      "growth",
      "variance"
    ],
    "aliases": [],
    "description": "Growth Target — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"14\" r=\"7\"/><circle cx=\"10\" cy=\"14\" r=\"3.6\"/><path d=\"M14.8 9.2 20 4M15 4h5v5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-receivables",
    "name": "Accounts Receivable",
    "primaryCategory": "variance",
    "keywords": [
      "receivables",
      "accounts",
      "receivable",
      "variance"
    ],
    "aliases": [],
    "description": "Accounts Receivable — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 2.5h12v19l-3-1.8-3 1.8-3-1.8-3 1.8V2.5Z\"/><path d=\"M9 11h3.5a2 2 0 1 0 0-4H9\"/><line x1=\"9\" y1=\"14.5\" x2=\"14\" y2=\"14.5\"/><line x1=\"16\" y1=\"6\" x2=\"19\" y2=\"6\"/><line x1=\"17.5\" y1=\"4.5\" x2=\"17.5\" y2=\"7.5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-payables",
    "name": "Accounts Payable",
    "primaryCategory": "variance",
    "keywords": [
      "payables",
      "accounts",
      "payable",
      "variance"
    ],
    "aliases": [],
    "description": "Accounts Payable — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 2.5h12v19l-3-1.8-3 1.8-3-1.8-3 1.8V2.5Z\"/><path d=\"M9 11h3.5a2 2 0 1 0 0-4H9\"/><line x1=\"9\" y1=\"14.5\" x2=\"14\" y2=\"14.5\"/><line x1=\"16\" y1=\"6.5\" x2=\"19\" y2=\"6.5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-cash-inflow",
    "name": "Cash Inflow",
    "primaryCategory": "variance",
    "keywords": [
      "cash",
      "inflow",
      "variance"
    ],
    "aliases": [],
    "description": "Cash Inflow — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"9.4\"/><line x1=\"12\" y1=\"7\" x2=\"12\" y2=\"17\"/><polyline points=\"8.5,10.5 12,7 15.5,10.5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-cash-outflow",
    "name": "Cash Outflow",
    "primaryCategory": "variance",
    "keywords": [
      "cash",
      "outflow",
      "variance"
    ],
    "aliases": [],
    "description": "Cash Outflow — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"9.4\"/><line x1=\"12\" y1=\"7\" x2=\"12\" y2=\"17\"/><polyline points=\"8.5,13.5 12,17 15.5,13.5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-aging-report",
    "name": "Aging Report",
    "primaryCategory": "variance",
    "keywords": [
      "aging",
      "report",
      "variance"
    ],
    "aliases": [],
    "description": "Aging Report — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"9.4\"/><polyline points=\"12,7 12,12 15.5,14\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-break-even",
    "name": "Break-even",
    "primaryCategory": "variance",
    "keywords": [
      "break",
      "even",
      "variance"
    ],
    "aliases": [],
    "description": "Break-even — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"3\" y1=\"12\" x2=\"21\" y2=\"12\"/><polyline points=\"3,20 12,12 21,4\"/><circle cx=\"12\" cy=\"12\" r=\"1.3\" fill=\"currentColor\" stroke=\"none\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-budget-vs-actual",
    "name": "Budget vs Actual",
    "primaryCategory": "variance",
    "keywords": [
      "budget",
      "vs",
      "actual",
      "variance"
    ],
    "aliases": [],
    "description": "Budget vs Actual — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"3\" y1=\"21\" x2=\"21\" y2=\"21\"/><rect x=\"4\" y=\"6\" width=\"5\" height=\"15\"/><rect x=\"14\" y=\"10\" width=\"5\" height=\"11\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-ratio-scale",
    "name": "Ratio / Comparison",
    "primaryCategory": "variance",
    "keywords": [
      "ratio",
      "scale",
      "comparison",
      "variance"
    ],
    "aliases": [],
    "description": "Ratio / Comparison — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"10\" width=\"7\" height=\"4\" rx=\"1\"/><rect x=\"14\" y=\"6\" width=\"7\" height=\"4\" rx=\"1\"/><rect x=\"14\" y=\"14\" width=\"7\" height=\"4\" rx=\"1\"/><line x1=\"10\" y1=\"12\" x2=\"14\" y2=\"8\"/><line x1=\"10\" y1=\"12\" x2=\"14\" y2=\"16\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-runway-forecast",
    "name": "Cash Runway",
    "primaryCategory": "variance",
    "keywords": [
      "runway",
      "forecast",
      "cash",
      "variance"
    ],
    "aliases": [],
    "description": "Cash Runway — professional growth, variance and financial metrics icon for Power BI dashboards.",
    "recommendedUses": [
      "Variance columns",
      "KPI trend indicators",
      "Finance tables"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"3\" y1=\"20\" x2=\"21\" y2=\"20\"/><path d=\"M4 18c3-1 5-4 6-8s3-6 6-6 5 3 5 8\"/><path d=\"M17 12l4-2v4Z\"/>",
    "source": "icon-vault"
  },
]
