// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const FINANCE_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-revenue",
    "name": "Revenue",
    "primaryCategory": "finance",
    "keywords": [
      "income",
      "sales",
      "money",
      "earnings",
      "finance",
      "revenue"
    ],
    "aliases": [],
    "description": "Revenue — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7.5v9M9.7 9.4c0-1.1 1-1.9 2.3-1.9 1.5 0 2.4.8 2.4 1.8 0 2.6-4.7 1.4-4.7 4 0 1.1 1 1.9 2.3 1.9s2.4-.8 2.4-1.9\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.16\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M12 7.5v9M9.7 9.4c0-1.1 1-1.9 2.3-1.9 1.5 0 2.4.8 2.4 1.8 0 2.6-4.7 1.4-4.7 4 0 1.1 1 1.9 2.3 1.9s2.4-.8 2.4-1.9\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-profit",
    "name": "Profit / Margin",
    "primaryCategory": "finance",
    "keywords": [
      "earnings",
      "net",
      "margin",
      "finance",
      "kpi",
      "profit"
    ],
    "aliases": [
      "Net Profit"
    ],
    "description": "Profit / Margin — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 17 9 11l3.5 3 7-8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M19.5 6h-3.5M19.5 6v3.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 20.5h16\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 17 9 11l3.5 3 7-8\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19.5 6h-3.5M19.5 6v3.5\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 20.5h16\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-cost",
    "name": "Cost / Expense",
    "primaryCategory": "finance",
    "keywords": [
      "spend",
      "expense",
      "outflow",
      "finance",
      "cost"
    ],
    "aliases": [],
    "description": "Cost / Expense — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3.5\" y=\"6\" width=\"17\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"2.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6.5 6v0M17.5 18v0\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3.5\" y=\"6\" width=\"17\" height=\"12\" rx=\"2\" fill=\"#E03131\" fill-opacity=\"0.1\" stroke=\"#E03131\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"2.4\" fill=\"#E03131\" fill-opacity=\"0.3\" stroke=\"#E03131\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-budget",
    "name": "Budget",
    "primaryCategory": "finance",
    "keywords": [
      "plan",
      "allocation",
      "finance",
      "spend",
      "budget"
    ],
    "aliases": [],
    "description": "Budget — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 9.5h17\" stroke=\"currentColor\"/><rect x=\"6\" y=\"12\" width=\"5\" height=\"4.5\" rx=\"0.8\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M3.5 9.5h17\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><rect x=\"6\" y=\"12\" width=\"5\" height=\"4.5\" rx=\"0.8\" fill=\"#4C6EF5\" fill-opacity=\"0.3\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><rect x=\"13\" y=\"12\" width=\"5\" height=\"4.5\" rx=\"0.8\" fill=\"#868E96\" fill-opacity=\"0.25\" stroke=\"#868E96\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-invoice",
    "name": "Invoice",
    "primaryCategory": "finance",
    "keywords": [
      "billing",
      "receipt",
      "document",
      "finance",
      "invoice"
    ],
    "aliases": [],
    "description": "Invoice — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 3.5h12v17l-2-1.4-2 1.4-2-1.4-2 1.4-2-1.4-2 1.4Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8.5 8h7M8.5 11.5h7M8.5 15h4\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 3.5h12v17l-2-1.4-2 1.4-2-1.4-2 1.4-2-1.4-2 1.4Z\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M8.5 8h7\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M8.5 11.5h7\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M8.5 15h4\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-currency-exchange",
    "name": "Currency Exchange",
    "primaryCategory": "finance",
    "keywords": [
      "forex",
      "conversion",
      "money",
      "exchange",
      "rate",
      "currency",
      "finance"
    ],
    "aliases": [],
    "description": "Currency Exchange — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 8h12M11.5 5 15.5 8 11.5 11\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M20.5 16h-12M12.5 13 8.5 16 12.5 19\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 8h12M11.5 5 15.5 8 11.5 11\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20.5 16h-12M12.5 13 8.5 16 12.5 19\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-wallet",
    "name": "Wallet",
    "primaryCategory": "finance",
    "keywords": [
      "money",
      "payment",
      "account",
      "finance",
      "wallet"
    ],
    "aliases": [],
    "description": "Wallet — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"6.5\" width=\"18\" height=\"13\" rx=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 10.5h18\" stroke=\"currentColor\"/><circle cx=\"16.5\" cy=\"14.5\" r=\"1.2\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"6.5\" width=\"18\" height=\"13\" rx=\"2.2\" fill=\"#F5A623\" fill-opacity=\"0.16\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M3 10.5h18\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><circle cx=\"16.5\" cy=\"14.5\" r=\"1.3\" fill=\"#F5A623\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-credit-card",
    "name": "Credit Card",
    "primaryCategory": "finance",
    "keywords": [
      "payment",
      "card",
      "banking",
      "finance",
      "credit"
    ],
    "aliases": [],
    "description": "Credit Card — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"5.5\" width=\"18\" height=\"13\" rx=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 9.5h18\" stroke=\"currentColor\"/><path d=\"M6 14.5h5\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"5.5\" width=\"18\" height=\"13\" rx=\"2.2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M3 9.5h18\" fill=\"#4C6EF5\" stroke=\"#4C6EF5\" stroke-width=\"3.2\"/><path d=\"M6 14.5h5\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-calculator",
    "name": "Calculator",
    "primaryCategory": "finance",
    "keywords": [
      "math",
      "compute",
      "finance",
      "accounting",
      "calculator"
    ],
    "aliases": [],
    "description": "Calculator — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"7.3\" y=\"5.3\" width=\"9.4\" height=\"3.6\" rx=\"0.7\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"12.5\" r=\"0.85\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"12.5\" r=\"0.85\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"12.5\" r=\"0.85\" fill=\"currentColor\"/><circle cx=\"8\" cy=\"16\" r=\"0.85\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"16\" r=\"0.85\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"16\" r=\"0.85\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><rect x=\"7.3\" y=\"5.3\" width=\"9.4\" height=\"3.6\" rx=\"0.7\" fill=\"#0CA678\" fill-opacity=\"0.25\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><circle cx=\"8\" cy=\"12.5\" r=\"0.9\" fill=\"#4C6EF5\"/><circle cx=\"12\" cy=\"12.5\" r=\"0.9\" fill=\"#4C6EF5\"/><circle cx=\"16\" cy=\"12.5\" r=\"0.9\" fill=\"#F08C00\"/><circle cx=\"8\" cy=\"16\" r=\"0.9\" fill=\"#4C6EF5\"/><circle cx=\"12\" cy=\"16\" r=\"0.9\" fill=\"#4C6EF5\"/><circle cx=\"16\" cy=\"16\" r=\"0.9\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-coins",
    "name": "Coins",
    "primaryCategory": "finance",
    "keywords": [
      "money",
      "cash",
      "savings",
      "finance",
      "coins"
    ],
    "aliases": [
      "Coin Stack"
    ],
    "description": "Coins — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<ellipse cx=\"9\" cy=\"8\" rx=\"5.5\" ry=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 8v4.5c0 1.7 2.5 3 5.5 3s5.5-1.3 5.5-3V8\" fill=\"none\" stroke=\"currentColor\"/><ellipse cx=\"15.5\" cy=\"14.5\" rx=\"4.7\" ry=\"2.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 14.5v3c0 1.3 2 2.4 4.5 2.4s4.5-1.1 4.5-2.4v-3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<ellipse cx=\"9\" cy=\"8\" rx=\"5.5\" ry=\"3\" fill=\"#F5A623\" fill-opacity=\"0.35\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M3.5 8v4.5c0 1.7 2.5 3 5.5 3s5.5-1.3 5.5-3V8\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><ellipse cx=\"15.5\" cy=\"14.5\" rx=\"4.7\" ry=\"2.4\" fill=\"#F08C00\" fill-opacity=\"0.35\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M11 14.5v3c0 1.3 2 2.4 4.5 2.4s4.5-1.1 4.5-2.4v-3\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-audit",
    "name": "Audit",
    "primaryCategory": "finance",
    "keywords": [
      "review",
      "compliance",
      "check",
      "finance",
      "audit"
    ],
    "aliases": [],
    "description": "Audit — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 3.5h9l3 3v14H6Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15 3.5v3h3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 13.5 11 15.5 15.5 11\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 3.5h9l3 3v14H6Z\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M15 3.5v3h3\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M9 13.5 11 15.5 15.5 11\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2.0\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-bank",
    "name": "Bank",
    "primaryCategory": "banking",
    "keywords": [
      "financial",
      "institution",
      "bank",
      "finance",
      "banking"
    ],
    "aliases": [],
    "description": "Bank — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 9.5 12 4l9 5.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 9.5h16V20H4Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 13v4M12 13v4M17 13v4\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3 9.5 12 4l9 5.5\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M4 9.5h16V20H4Z\" fill=\"#F5A623\" fill-opacity=\"0.14\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M7 13v4M12 13v4M17 13v4\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-insurance-policy",
    "name": "Insurance Policy",
    "primaryCategory": "banking",
    "keywords": [
      "coverage",
      "protection",
      "policy",
      "insurance",
      "banking"
    ],
    "aliases": [],
    "description": "Insurance Policy — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 19 6v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 12.3 11.2 14.5 15.5 9.7\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3 19 6v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6Z\" fill=\"#4C6EF5\" fill-opacity=\"0.18\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M9 12.3 11.2 14.5 15.5 9.7\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2.0\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-loan",
    "name": "Loan / Mortgage",
    "primaryCategory": "banking",
    "keywords": [
      "lending",
      "credit",
      "mortgage",
      "finance",
      "loan",
      "banking"
    ],
    "aliases": [],
    "description": "Loan / Mortgage — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 10 12 4l9 6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 10v10h14V10\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 20v-6h4v6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"13.5\" r=\"0.3\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3 10 12 4l9 6\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M5 10v10h14V10\" fill=\"#868E96\" fill-opacity=\"0.1\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M10 20v-6h4v6\" fill=\"#F5A623\" fill-opacity=\"0.3\" stroke=\"#F5A623\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-tax",
    "name": "Tax",
    "primaryCategory": "finance",
    "keywords": [
      "percent",
      "document",
      "filing",
      "tax",
      "finance"
    ],
    "aliases": [],
    "description": "Tax — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 3H15L18 6V21H6Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9.5 10.5 14.5 15.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9.7\" cy=\"10.7\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"14.3\" cy=\"15.3\" r=\"0.9\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 3H15L18 6V21H6Z\" fill=\"#0CA678\" fill-opacity=\"0.1\"/><path d=\"M6 3H15L18 6V21H6Z\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9.5 10.5 14.5 15.5\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"9.7\" cy=\"10.7\" r=\"1\" fill=\"#2B2D42\"/><circle cx=\"14.3\" cy=\"15.3\" r=\"1\" fill=\"#2B2D42\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-loss",
    "name": "Loss",
    "primaryCategory": "finance",
    "keywords": [
      "decline",
      "drop",
      "money",
      "down",
      "loss",
      "finance"
    ],
    "aliases": [],
    "description": "Loss — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8.5 10 11 13 13 11 16 15\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M14 15H16V13\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#E03131\" fill-opacity=\"0.12\" stroke=\"#E03131\" stroke-width=\"1.6\"/><path d=\"M8.5 10 11 13 13 11 16 15\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 15H16V13\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-exchange-rate",
    "name": "Exchange Rate",
    "primaryCategory": "finance",
    "keywords": [
      "currency",
      "convert",
      "forex",
      "exchange",
      "rate",
      "finance"
    ],
    "aliases": [],
    "description": "Exchange Rate — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M5 9H17L14 6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M19 15H7L10 18\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"9\" r=\"0\" fill=\"currentColor\"/><path d=\"M5 9H17L14 6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M19 15H7L10 18\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 9H17L14 6\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 15H7L10 18\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-piggy-bank",
    "name": "Piggy Bank",
    "primaryCategory": "banking",
    "keywords": [
      "savings",
      "money",
      "deposit",
      "piggy",
      "bank",
      "banking"
    ],
    "aliases": [],
    "description": "Piggy Bank — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 13a6 5 0 0 1 12 0v3h2l1-3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 9a8 8 0 0 0-3-1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 18v1.5M13 18v1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 7.5 11 7.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"15\" cy=\"12\" r=\"0.9\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 13a6 5 0 0 1 12 0v3h2l1-3\" fill=\"#F08C00\" fill-opacity=\"0.18\"/><path d=\"M4 13a6 5 0 0 1 12 0v3h2l1-3\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 9a8 8 0 0 0-3-1\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 18v1.5M13 18v1.5\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"15\" cy=\"12\" r=\"0.9\" fill=\"#2B2D42\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-atm",
    "name": "ATM",
    "primaryCategory": "banking",
    "keywords": [
      "cash",
      "machine",
      "withdraw",
      "atm",
      "banking"
    ],
    "aliases": [],
    "description": "ATM — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8\" y=\"6\" width=\"8\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 14H16M8 17H12\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.1\"/><rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"8\" y=\"6\" width=\"8\" height=\"5\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.25\"/><path d=\"M8 14H16M8 17H12\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-mortgage",
    "name": "Mortgage",
    "primaryCategory": "banking",
    "keywords": [
      "home",
      "loan",
      "property",
      "finance",
      "mortgage",
      "banking"
    ],
    "aliases": [],
    "description": "Mortgage — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 11 12 5 20 11\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 11V19H18V11\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"15\" r=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 14V16M11.2 15H12.8\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 11 12 5 20 11\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 11V19H18V11\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"15\" r=\"2\" fill=\"#F08C00\" fill-opacity=\"0.25\" stroke=\"#F08C00\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ledger",
    "name": "Ledger",
    "primaryCategory": "finance",
    "keywords": [
      "accounts",
      "book",
      "records",
      "ledger",
      "finance"
    ],
    "aliases": [],
    "description": "Ledger — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 4V20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 9H17M11 12H17M11 15H15\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 4V20\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11 9H17M11 12H17M11 15H15\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-cash-flow",
    "name": "Cash Flow",
    "primaryCategory": "finance",
    "keywords": [
      "liquidity",
      "inflow",
      "outflow",
      "statement",
      "cash",
      "flow",
      "finance"
    ],
    "aliases": [],
    "description": "Cash Flow — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 16 10 10 14 13 20 8\" fill=\"none\" stroke=\"#0CA678\"/><path d=\"M6 18 10 15 14 17 20 14\" fill=\"none\" stroke=\"#E03131\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 16 10 10 14 13 20 8\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 18 10 15 14 17 20 14\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-balance-sheet",
    "name": "Balance Sheet",
    "primaryCategory": "finance",
    "keywords": [
      "assets",
      "liabilities",
      "equity",
      "balance",
      "sheet",
      "finance"
    ],
    "aliases": [],
    "description": "Balance Sheet — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 4V20M4 12H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 8h4M6 16h4M14 8h4M14 16h4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"8\" height=\"8\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"12\" y=\"4\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.15\"/><rect x=\"4\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.15\"/><rect x=\"12\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#868E96\" fill-opacity=\"0.15\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-income-statement",
    "name": "Income Statement",
    "primaryCategory": "finance",
    "keywords": [
      "pnl",
      "revenue",
      "expense",
      "profit",
      "income",
      "statement",
      "finance"
    ],
    "aliases": [],
    "description": "Income Statement — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 7h8M8 10h8M8 13h5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 17h4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 3h14v18H5Z\" fill=\"#4C6EF5\" fill-opacity=\"0.07\" stroke=\"none\"/><rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 7h8M8 10h8M8 13h5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M8 17h4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-depreciation",
    "name": "Depreciation",
    "primaryCategory": "finance",
    "keywords": [
      "asset",
      "value",
      "decline",
      "reduce",
      "depreciation",
      "finance"
    ],
    "aliases": [],
    "description": "Depreciation — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 5H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 5 8 12 13 16 20 18\" fill=\"none\" stroke=\"#E03131\"/><path d=\"M18 18h2M18 16v2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 5H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 5 8 12 13 16 20 18\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 18h2M18 16v2\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-amortization",
    "name": "Amortization",
    "primaryCategory": "finance",
    "keywords": [
      "loan",
      "payment",
      "schedule",
      "reduce",
      "amortization",
      "finance"
    ],
    "aliases": [],
    "description": "Amortization — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 12 7 7\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 4v2M20 12h-2M12 20v-2M4 12h2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"#4C6EF5\" fill-opacity=\"0.1\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 12 7 7\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 4v2M20 12h-2M12 20v-2M4 12h2\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-roi",
    "name": "ROI",
    "primaryCategory": "finance",
    "keywords": [
      "return",
      "investment",
      "ratio",
      "gain",
      "roi",
      "finance"
    ],
    "aliases": [],
    "description": "ROI — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12h8M12 8v8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 8l1.5-1.5M6 16.5l1.5-1.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.1\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M8 12h8M12 8v8\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 8l1.5-1.5\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-irr",
    "name": "IRR",
    "primaryCategory": "finance",
    "keywords": [
      "internal",
      "rate",
      "return",
      "discount",
      "irr",
      "finance"
    ],
    "aliases": [],
    "description": "IRR — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 18 8 10 12 14 16 6 20 9\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 18H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 6l2-2M18 6l-2-2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 18 8 10 12 14 16 6 20 9\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 18H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 6l2-2M18 6l-2-2\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-npv",
    "name": "NPV",
    "primaryCategory": "finance",
    "keywords": [
      "net",
      "present",
      "value",
      "discount",
      "cash",
      "npv",
      "finance"
    ],
    "aliases": [],
    "description": "NPV — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"10\" width=\"16\" height=\"10\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 10V7a5 5 0 0 1 10 0v3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 14v3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"14\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"10\" width=\"16\" height=\"10\" rx=\"1.5\" fill=\"#F5A623\" fill-opacity=\"0.2\"/><rect x=\"4\" y=\"10\" width=\"16\" height=\"10\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 10V7a5 5 0 0 1 10 0v3\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 14v3\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-variance",
    "name": "Variance",
    "primaryCategory": "finance",
    "keywords": [
      "difference",
      "plan",
      "actual",
      "delta",
      "variance",
      "finance"
    ],
    "aliases": [],
    "description": "Variance — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"6\" width=\"5\" height=\"8\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"10\" width=\"5\" height=\"5\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8.5 6v8M15.5 10v5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 3l5 3M13 8l5 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"6\" y=\"6\" width=\"5\" height=\"8\" rx=\"0.5\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"13\" y=\"10\" width=\"5\" height=\"5\" rx=\"0.5\" fill=\"#E03131\" fill-opacity=\"0.85\"/><path d=\"M6 3l5 3\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M13 8l5 2\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-working-capital",
    "name": "Working Capital",
    "primaryCategory": "finance",
    "keywords": [
      "current",
      "assets",
      "liquidity",
      "ratio",
      "working",
      "capital",
      "finance"
    ],
    "aliases": [],
    "description": "Working Capital — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9h8M8 12h6M8 15h4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 7l2 2-2 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"#1C7ED6\" fill-opacity=\"0.1\" stroke=\"#1C7ED6\" stroke-width=\"1.6\"/><path d=\"M8 9h8M8 12h6M8 15h4\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 7l2 2-2 2\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-debt-ratio",
    "name": "Debt Ratio",
    "primaryCategory": "finance",
    "keywords": [
      "leverage",
      "solvency",
      "liabilities",
      "debt",
      "ratio",
      "finance"
    ],
    "aliases": [],
    "description": "Debt Ratio — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 4A8 8 0 0 1 20 12H12Z\" fill=\"#E03131\" fill-opacity=\"0.8\" stroke=\"none\"/><path d=\"M12 4A8 8 0 0 0 4 12H12Z\" fill=\"#0CA678\" fill-opacity=\"0.8\" stroke=\"none\"/><path d=\"M12 4V20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"#E03131\" fill-opacity=\"0.15\" stroke=\"#E03131\" stroke-width=\"1.6\"/><path d=\"M12 4A8 8 0 0 1 20 12H12Z\" fill=\"#E03131\" fill-opacity=\"0.6\" stroke=\"none\"/><path d=\"M12 4A8 8 0 0 0 4 12H12Z\" fill=\"#0CA678\" fill-opacity=\"0.6\" stroke=\"none\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ebitda",
    "name": "EBITDA",
    "primaryCategory": "finance",
    "keywords": [
      "earnings",
      "margin",
      "operating",
      "profit",
      "ebitda",
      "finance"
    ],
    "aliases": [],
    "description": "EBITDA — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9h8M8 12h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 15l2 2 4-4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 5h16v14H4Z\" fill=\"#0CA678\" fill-opacity=\"0.08\" stroke=\"none\"/><rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 9h8M8 12h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M8 15l2 2 4-4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-capex",
    "name": "CapEx",
    "primaryCategory": "finance",
    "keywords": [
      "capital",
      "expenditure",
      "invest",
      "asset",
      "capex",
      "finance"
    ],
    "aliases": [],
    "description": "CapEx — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"12\" width=\"16\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 12V8a5 5 0 0 1 10 0v4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 15v2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"15\" r=\"1.1\" fill=\"currentColor\"/><path d=\"M9 5l3-3 3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"12\" width=\"16\" height=\"8\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"4\" y=\"12\" width=\"16\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 12V8a5 5 0 0 1 10 0v4\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 5l3-3 3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-opex",
    "name": "OpEx",
    "primaryCategory": "finance",
    "keywords": [
      "operational",
      "expenditure",
      "recurring",
      "cost",
      "opex",
      "finance"
    ],
    "aliases": [],
    "description": "OpEx — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 8v4l-3 3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 4v1.5M20 12h-1.5M12 20v-1.5M4 12h1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 12V8l3 3-3 3Z\" fill=\"#F08C00\" fill-opacity=\"0.7\" stroke=\"none\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"#F08C00\" fill-opacity=\"0.1\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M12 8v4l-3 3\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 4v1.5M20 12h-1.5M12 20v-1.5M4 12h1.5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-financial-ratio",
    "name": "Financial Ratio",
    "primaryCategory": "finance",
    "keywords": [
      "metric",
      "indicator",
      "measure",
      "formula",
      "financial",
      "ratio",
      "finance"
    ],
    "aliases": [],
    "description": "Financial Ratio — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"9\" cy=\"9\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"15\" cy=\"15\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M13 11 11 13\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9\" cy=\"9\" r=\"1\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"15\" r=\"1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"9\" cy=\"9\" r=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"15\" cy=\"15\" r=\"5\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M13 11 11 13\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-credit-score",
    "name": "Credit Score",
    "primaryCategory": "banking",
    "keywords": [
      "rating",
      "cibil",
      "bureau",
      "risk",
      "score",
      "credit",
      "banking"
    ],
    "aliases": [],
    "description": "Credit Score — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5A8.5 8.5 0 0 1 20.5 12H12Z\" fill=\"#0CA678\" fill-opacity=\"0.85\" stroke=\"none\"/><path d=\"M12 3.5A8.5 8.5 0 0 0 3.5 12H12Z\" fill=\"#F08C00\" fill-opacity=\"0.85\" stroke=\"none\"/><path d=\"M3.5 12A8.5 8.5 0 0 0 12 20.5V12Z\" fill=\"#E03131\" fill-opacity=\"0.85\" stroke=\"none\"/><path d=\"M12 12h8.5A8.5 8.5 0 0 1 12 20.5Z\" fill=\"#868E96\" fill-opacity=\"0.3\" stroke=\"none\"/><circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\" fill=\"#2B2D42\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M12 3.5A8.5 8.5 0 0 1 20.5 12H12Z\" fill=\"#0CA678\" fill-opacity=\"0.9\" stroke=\"none\"/><path d=\"M12 3.5A8.5 8.5 0 0 0 3.5 12H12Z\" fill=\"#F08C00\" fill-opacity=\"0.9\" stroke=\"none\"/><path d=\"M3.5 12A8.5 8.5 0 0 0 12 20.5V12Z\" fill=\"#E03131\" fill-opacity=\"0.9\" stroke=\"none\"/><circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-wire-transfer",
    "name": "Wire Transfer",
    "primaryCategory": "banking",
    "keywords": [
      "send",
      "receive",
      "remit",
      "swift",
      "funds",
      "wire",
      "transfer",
      "banking"
    ],
    "aliases": [],
    "description": "Wire Transfer — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"8\" width=\"16\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 8V5l3-2 3 2v3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 12v4M9.5 15h5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 4l3 3-3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"8\" width=\"16\" height=\"8\" rx=\"2\" fill=\"#1C7ED6\" fill-opacity=\"0.12\"/><rect x=\"4\" y=\"8\" width=\"16\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M12 12v4M9.5 15h5\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 4l3 3-3 3\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-interest-rate",
    "name": "Interest Rate",
    "primaryCategory": "banking",
    "keywords": [
      "percent",
      "base",
      "repo",
      "rate",
      "cost",
      "interest",
      "banking"
    ],
    "aliases": [],
    "description": "Interest Rate — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 9l6 6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9.5\" cy=\"9.5\" r=\"1.1\" fill=\"#F5A623\"/><circle cx=\"14.5\" cy=\"14.5\" r=\"1.1\" fill=\"#F5A623\"/><path d=\"M12 3.5v1.5M20.5 12H19\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#F5A623\" fill-opacity=\"0.1\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M9 9l6 6\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"9.5\" cy=\"9.5\" r=\"1.2\" fill=\"#F5A623\"/><circle cx=\"14.5\" cy=\"14.5\" r=\"1.2\" fill=\"#F5A623\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-kyc",
    "name": "KYC",
    "primaryCategory": "banking",
    "keywords": [
      "verify",
      "identity",
      "aml",
      "onboard",
      "due",
      "diligence",
      "kyc",
      "banking"
    ],
    "aliases": [
      "Customer Onboarding",
      "Onboarding Cx"
    ],
    "description": "KYC — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 5l2 2 4-4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 11l2 2 4-4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 5l2 2 4-4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 11l2 2 4-4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-card-transaction",
    "name": "Card Transaction",
    "primaryCategory": "banking",
    "keywords": [
      "credit",
      "debit",
      "swipe",
      "pay",
      "contactless",
      "card",
      "transaction",
      "banking"
    ],
    "aliases": [],
    "description": "Card Transaction — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"7\" width=\"18\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 11h18\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 15h3M12 15h2\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"7\" width=\"4\" height=\"4\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"7\" width=\"18\" height=\"4\" rx=\"2\" fill=\"#4C6EF5\"/><rect x=\"3\" y=\"11\" width=\"18\" height=\"6\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.08\"/><rect x=\"3\" y=\"7\" width=\"18\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M6 15h3M12 15h2\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-forex",
    "name": "Forex Trading",
    "primaryCategory": "banking",
    "keywords": [
      "foreign",
      "exchange",
      "currency",
      "pair",
      "trade",
      "forex",
      "trading",
      "banking"
    ],
    "aliases": [],
    "description": "Forex Trading — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"9\" cy=\"9\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"15\" cy=\"15\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M13 11 11 13\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 7l1.5-1.5M17 17l1.5 1.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"9\" cy=\"9\" r=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"15\" cy=\"15\" r=\"5\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M13 11 11 13\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-trade-finance",
    "name": "Trade Finance",
    "primaryCategory": "banking",
    "keywords": [
      "lc",
      "letter",
      "credit",
      "export",
      "import",
      "trade",
      "finance",
      "banking"
    ],
    "aliases": [],
    "description": "Trade Finance — professional banking and insurance icon for Power BI dashboards.",
    "recommendedUses": [
      "Banking dashboards",
      "Risk reports",
      "Product KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 10H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 14h10M7 17h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M14 7l2 2-2 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 5h16v5H4Z\" fill=\"#F5A623\" fill-opacity=\"0.2\" stroke=\"none\"/><rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M4 10H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 14h10M7 17h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 7l2 2-2 2\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-fx-exposure",
    "name": "FX Exposure",
    "primaryCategory": "finance",
    "keywords": [
      "currency",
      "risk",
      "hedge",
      "foreign",
      "fx",
      "exposure",
      "finance"
    ],
    "aliases": [],
    "description": "FX Exposure — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 10 9 8 13 10 17 8\" fill=\"none\" stroke=\"#E03131\"/><path d=\"M5 14 9 12 13 14 17 12\" fill=\"none\" stroke=\"#0CA678\"/><path d=\"M12 3.5v1M20.5 12H19\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#F08C00\" fill-opacity=\"0.08\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M5 10 9 8 13 10 17 8\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 14 9 12 13 14 17 12\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-safe",
    "name": "Safe / Vault",
    "primaryCategory": "finance",
    "keywords": [
      "safe",
      "vault",
      "finance"
    ],
    "aliases": [],
    "description": "Safe / Vault — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"4\"/><line x1=\"12\" y1=\"12\" x2=\"14.5\" y2=\"10\"/><circle cx=\"12\" cy=\"12\" r=\"0.8\" fill=\"currentColor\" stroke=\"none\"/><line x1=\"6\" y1=\"4\" x2=\"6\" y2=\"7\"/><line x1=\"18\" y1=\"4\" x2=\"18\" y2=\"7\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-banknote",
    "name": "Banknote",
    "primaryCategory": "finance",
    "keywords": [
      "banknote",
      "finance"
    ],
    "aliases": [],
    "description": "Banknote — professional finance and accounting icon for Power BI dashboards.",
    "recommendedUses": [
      "Financial dashboards",
      "P&L report headers",
      "KPI cards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"2\" y=\"6\" width=\"20\" height=\"12\" rx=\"1.5\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/><circle cx=\"5\" cy=\"9\" r=\"0.6\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"19\" cy=\"15\" r=\"0.6\" fill=\"currentColor\" stroke=\"none\"/>",
    "source": "icon-vault"
  },
]
