// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const HR_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-employee",
    "name": "Employee",
    "primaryCategory": "hr",
    "keywords": [
      "staff",
      "person",
      "worker",
      "hr",
      "headcount",
      "employee"
    ],
    "aliases": [
      "User"
    ],
    "description": "Employee — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"7.5\" r=\"3.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 20c0-3.6 3.1-6.5 7-6.5s7 2.9 7 6.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"9.6\" y=\"18.4\" width=\"4.8\" height=\"2.4\" rx=\"0.6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"7.5\" r=\"3.4\" fill=\"#7048E8\" fill-opacity=\"0.25\" stroke=\"#7048E8\" stroke-width=\"1.6\"/><path d=\"M5 20c0-3.6 3.1-6.5 7-6.5s7 2.9 7 6.5\" fill=\"#7048E8\" fill-opacity=\"0.14\" stroke=\"#7048E8\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-team",
    "name": "Team",
    "primaryCategory": "hr",
    "keywords": [
      "group",
      "people",
      "staff",
      "department",
      "hr",
      "team"
    ],
    "aliases": [],
    "description": "Team — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"8.5\" cy=\"8\" r=\"2.8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"16\" cy=\"8\" r=\"2.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 19c0-3 2.4-5.3 5-5.3s5 2.3 5 5.3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M14.3 14c2.3.3 4.2 2.4 4.2 5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"8.5\" cy=\"8\" r=\"2.8\" fill=\"#4C6EF5\" fill-opacity=\"0.3\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"16\" cy=\"8\" r=\"2.4\" fill=\"#868E96\" fill-opacity=\"0.3\" stroke=\"#868E96\" stroke-width=\"1.6\"/><path d=\"M3.5 19c0-3 2.4-5.3 5-5.3s5 2.3 5 5.3\" fill=\"#4C6EF5\" fill-opacity=\"0.14\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M14.3 14c2.3.3 4.2 2.4 4.2 5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-recruitment",
    "name": "Recruitment",
    "primaryCategory": "hr",
    "keywords": [
      "hiring",
      "talent",
      "acquisition",
      "hr",
      "recruitment"
    ],
    "aliases": [],
    "description": "Recruitment — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"9\" r=\"3.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 20c0-3.5 2.9-6.2 6.5-6.2s6.5 2.7 6.5 6.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 5v6M15 8h6\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"9\" r=\"3.2\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M3.5 20c0-3.5 2.9-6.2 6.5-6.2s6.5 2.7 6.5 6.2\" fill=\"#4C6EF5\" fill-opacity=\"0.12\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M18 5v6M15 8h6\" stroke=\"#0CA678\" stroke-width=\"1.9000000000000001\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-attendance",
    "name": "Attendance",
    "primaryCategory": "hr",
    "keywords": [
      "timesheet",
      "clock",
      "checkin",
      "hr",
      "attendance"
    ],
    "aliases": [],
    "description": "Attendance — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15.5\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 9.5h17\" stroke=\"currentColor\"/><path d=\"M8 3v4M16 3v4\" stroke=\"currentColor\"/><path d=\"M9 14.5l2 2 4-4.2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15.5\" rx=\"2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M3.5 9.5h17\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M8 3v4M16 3v4\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M9 14.5l2 2 4-4.2\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.9000000000000001\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-payroll",
    "name": "Payroll",
    "primaryCategory": "hr",
    "keywords": [
      "salary",
      "compensation",
      "pay",
      "hr",
      "payroll"
    ],
    "aliases": [],
    "description": "Payroll — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3.5\" y=\"6\" width=\"17\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"2.6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6.5 9v0M17.5 15v0\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3.5\" y=\"6\" width=\"17\" height=\"12\" rx=\"2\" fill=\"#F5A623\" fill-opacity=\"0.12\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"2.6\" fill=\"#F5A623\" fill-opacity=\"0.35\" stroke=\"#F5A623\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-org-chart",
    "name": "Org Chart",
    "primaryCategory": "hr",
    "keywords": [
      "hierarchy",
      "structure",
      "organization",
      "hr",
      "org",
      "chart"
    ],
    "aliases": [],
    "description": "Org Chart — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"9\" y=\"3\" width=\"6\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"3\" y=\"15\" width=\"6\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"15\" y=\"15\" width=\"6\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7v4.5M6 15v-3.5h12V15\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"9\" y=\"3\" width=\"6\" height=\"4\" rx=\"1\" fill=\"#2B2D42\" fill-opacity=\"0.18\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><rect x=\"3\" y=\"15\" width=\"6\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><rect x=\"15\" y=\"15\" width=\"6\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 7v4.5M6 15v-3.5h12V15\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-training",
    "name": "Training",
    "primaryCategory": "hr",
    "keywords": [
      "learning",
      "development",
      "education",
      "hr",
      "training"
    ],
    "aliases": [],
    "description": "Training — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 7 12 3l9 4-9 4-9-4Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 9.5v4.5c0 1.7 2.2 3 5 3s5-1.3 5-3V9.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M21 7v6\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3 7 12 3l9 4-9 4-9-4Z\" fill=\"#7048E8\" fill-opacity=\"0.22\" stroke=\"#7048E8\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M7 9.5v4.5c0 1.7 2.2 3 5 3s5-1.3 5-3V9.5\" fill=\"none\" stroke=\"#7048E8\" stroke-width=\"1.6\"/><path d=\"M21 7v6\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-onboarding",
    "name": "Onboarding",
    "primaryCategory": "hr",
    "keywords": [
      "welcome",
      "new",
      "employee",
      "join",
      "onboarding",
      "hr"
    ],
    "aliases": [],
    "description": "Onboarding — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 12h6l-2-2M22 12l-2 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 12h6l-2-2M22 12l-2 2\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-performance-review",
    "name": "Performance Review",
    "primaryCategory": "hr",
    "keywords": [
      "appraisal",
      "rating",
      "employee",
      "performance",
      "review",
      "hr"
    ],
    "aliases": [],
    "description": "Performance Review — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"9\" cy=\"8\" r=\"3.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 6l1 2 2 .3-1.5 1.4.4 2.3-1.9-1-1.9 1 .4-2.3L13 8.3 15 8Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"9\" cy=\"8\" r=\"3.5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M3 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 6l1 2 2 .3-1.5 1.4.4 2.3-1.9-1-1.9 1 .4-2.3L13 8.3 15 8Z\" fill=\"#F5A623\" stroke=\"#F5A623\" stroke-width=\"0.8\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-benefits",
    "name": "Benefits",
    "primaryCategory": "hr",
    "keywords": [
      "perks",
      "insurance",
      "heart",
      "shield",
      "benefits",
      "hr"
    ],
    "aliases": [],
    "description": "Benefits — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 11h2V9h2v2h2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10Z\" fill=\"#E03131\" fill-opacity=\"0.15\"/><path d=\"M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10Z\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 11h2V9h2v2h2\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-resignation",
    "name": "Resignation",
    "primaryCategory": "hr",
    "keywords": [
      "exit",
      "leave",
      "employee",
      "door",
      "resignation",
      "hr"
    ],
    "aliases": [],
    "description": "Resignation — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M14 4H6v16h8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 12h9l-3-3M19 12l-3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M14 4H6v16h8\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 12h9l-3-3M19 12l-3 3\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-timesheet",
    "name": "Timesheet",
    "primaryCategory": "hr",
    "keywords": [
      "hours",
      "log",
      "work",
      "record",
      "timesheet",
      "hr"
    ],
    "aliases": [],
    "description": "Timesheet — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 9H20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8.5\" cy=\"14.5\" r=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8.5 13.5V14.5L9.3 15\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M13 13H17M13 16H16\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"5\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"8.5\" cy=\"14.5\" r=\"2.2\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M13 13H17M13 16H16\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-diversity",
    "name": "Diversity",
    "primaryCategory": "hr",
    "keywords": [
      "inclusion",
      "people",
      "group",
      "equity",
      "diversity",
      "hr"
    ],
    "aliases": [],
    "description": "Diversity — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"9\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"9\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"8\" r=\"2.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 18a4 4 0 0 1 8 0M13 18a4 4 0 0 1 8 0M7.5 17a4.5 4.5 0 0 1 9 0\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"9\" r=\"2.5\" fill=\"#4C6EF5\"/><circle cx=\"17\" cy=\"9\" r=\"2.5\" fill=\"#0CA678\"/><circle cx=\"12\" cy=\"8\" r=\"2.8\" fill=\"#F08C00\"/><path d=\"M3 18a4 4 0 0 1 8 0M13 18a4 4 0 0 1 8 0M7.5 17a4.5 4.5 0 0 1 9 0\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-headcount",
    "name": "Headcount",
    "primaryCategory": "hr",
    "keywords": [
      "staff",
      "count",
      "employees",
      "total",
      "workforce",
      "headcount",
      "hr"
    ],
    "aliases": [],
    "description": "Headcount — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"8\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"8\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"8\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M2 19a5 5 0 0 1 10 0M12 19a5 5 0 0 1 10 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 19a5 5 0 0 1 10 0\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"8\" r=\"3\" fill=\"#4C6EF5\"/><circle cx=\"17\" cy=\"8\" r=\"3\" fill=\"#0CA678\"/><circle cx=\"12\" cy=\"8\" r=\"3\" fill=\"#7048E8\"/><path d=\"M7 19a5 5 0 0 1 10 0\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-attrition",
    "name": "Attrition Rate",
    "primaryCategory": "hr",
    "keywords": [
      "turnover",
      "exit",
      "leave",
      "reduce",
      "attrition",
      "rate",
      "hr"
    ],
    "aliases": [],
    "description": "Attrition Rate — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 5l4 4M22 5l-4 4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"#E03131\" fill-opacity=\"0.15\" stroke=\"#E03131\" stroke-width=\"1.6\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 5l4 4M22 5l-4 4\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-succession",
    "name": "Succession Planning",
    "primaryCategory": "hr",
    "keywords": [
      "pipeline",
      "talent",
      "future",
      "leader",
      "succession",
      "planning",
      "hr"
    ],
    "aliases": [],
    "description": "Succession Planning — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"6\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"16\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"16\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 9v4M12 13l-5 3M12 13l5 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"6\" r=\"3\" fill=\"#F5A623\" fill-opacity=\"0.2\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><circle cx=\"7\" cy=\"16\" r=\"2.5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"16\" r=\"2.5\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M12 9v4M12 13l-5 3M12 13l5 3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-engagement",
    "name": "Employee Engagement",
    "primaryCategory": "hr",
    "keywords": [
      "morale",
      "satisfaction",
      "pulse",
      "culture",
      "engagement",
      "employee",
      "hr"
    ],
    "aliases": [],
    "description": "Employee Engagement — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"10\" r=\"6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 13a3 3 0 0 0 6 0\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"10\" cy=\"9\" r=\"1\" fill=\"currentColor\"/><circle cx=\"14\" cy=\"9\" r=\"1\" fill=\"currentColor\"/><path d=\"M12 4v1M12 16v4M8 21h8\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"10\" r=\"6\" fill=\"#0CA678\" fill-opacity=\"0.12\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M9 13a3 3 0 0 0 6 0\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"10\" cy=\"9\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"9\" r=\"1.2\" fill=\"#4C6EF5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-wellness",
    "name": "Employee Wellness",
    "primaryCategory": "hr",
    "keywords": [
      "health",
      "wellbeing",
      "program",
      "mental",
      "wellness",
      "employee",
      "hr"
    ],
    "aliases": [
      "Public Health"
    ],
    "description": "Employee Wellness — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 21s-7-4.5-7-9a4 4 0 0 1 7-2.5A4 4 0 0 1 19 12c0 4.5-7 9-7 9Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 11h2V9h2v2h2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 21s-7-4.5-7-9a4 4 0 0 1 7-2.5A4 4 0 0 1 19 12c0 4.5-7 9-7 9Z\" fill=\"#E03131\" fill-opacity=\"0.15\" stroke=\"none\"/><path d=\"M12 21s-7-4.5-7-9a4 4 0 0 1 7-2.5A4 4 0 0 1 19 12c0 4.5-7 9-7 9Z\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 11h2V9h2v2h2\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-remote-work",
    "name": "Remote Work",
    "primaryCategory": "hr",
    "keywords": [
      "home",
      "office",
      "hybrid",
      "wfh",
      "remote",
      "work",
      "hr"
    ],
    "aliases": [],
    "description": "Remote Work — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"13\" width=\"18\" height=\"7\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 13V10a3 3 0 0 1 6 0v3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 13h10\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"6\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"6\" r=\"2.5\" fill=\"#1C7ED6\" fill-opacity=\"0.15\" stroke=\"#1C7ED6\" stroke-width=\"1.6\"/><rect x=\"3\" y=\"13\" width=\"18\" height=\"7\" rx=\"2\" fill=\"#1C7ED6\" fill-opacity=\"0.12\"/><rect x=\"3\" y=\"13\" width=\"18\" height=\"7\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M9 13V10a3 3 0 0 1 6 0v3\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-shift",
    "name": "Shift Schedule",
    "primaryCategory": "hr",
    "keywords": [
      "roster",
      "work",
      "hours",
      "shift",
      "swap",
      "schedule",
      "hr"
    ],
    "aliases": [],
    "description": "Shift Schedule — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 9H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 4V9M15 4V9\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"12\" width=\"5\" height=\"4\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"12\" width=\"5\" height=\"4\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"5\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"6\" y=\"12\" width=\"5\" height=\"4\" rx=\"0.5\" fill=\"#F08C00\" fill-opacity=\"0.7\"/><rect x=\"13\" y=\"12\" width=\"5\" height=\"4\" rx=\"0.5\" fill=\"#0CA678\" fill-opacity=\"0.7\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-exit-interview",
    "name": "Exit Interview",
    "primaryCategory": "hr",
    "keywords": [
      "offboard",
      "feedback",
      "leave",
      "reason",
      "exit",
      "interview",
      "hr"
    ],
    "aliases": [],
    "description": "Exit Interview — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"11\" width=\"8\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 14v3M18.5 14v3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"19\" r=\"0.8\" fill=\"currentColor\"/><circle cx=\"18.5\" cy=\"19\" r=\"0.8\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"8\" r=\"4\" fill=\"#868E96\" fill-opacity=\"0.15\" stroke=\"#868E96\" stroke-width=\"1.6\"/><path d=\"M4 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"14\" y=\"11\" width=\"8\" height=\"8\" rx=\"1.5\" fill=\"#F08C00\" fill-opacity=\"0.15\"/><rect x=\"14\" y=\"11\" width=\"8\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-labor-cost",
    "name": "Labor Cost",
    "primaryCategory": "hr",
    "keywords": [
      "salary",
      "spend",
      "budget",
      "workforce",
      "labor",
      "cost",
      "hr"
    ],
    "aliases": [],
    "description": "Labor Cost — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"9\" cy=\"8\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 10v9M14.5 12h5M14.5 15h3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"9\" cy=\"8\" r=\"4\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M3 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 10v9M14.5 12h5M14.5 15h3\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-feedback",
    "name": "360 Feedback",
    "primaryCategory": "hr",
    "keywords": [
      "review",
      "peer",
      "multi-rater",
      "assess",
      "feedback",
      "360",
      "hr"
    ],
    "aliases": [
      "Feedback"
    ],
    "description": "360 Feedback — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"3.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 8.5a8 8 0 0 1 0 7M8.5 12a8 8 0 0 1 7 0\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"4\" r=\"1\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"20\" r=\"1\" fill=\"currentColor\"/><circle cx=\"4\" cy=\"12\" r=\"1\" fill=\"currentColor\"/><circle cx=\"20\" cy=\"12\" r=\"1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"3.5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 8.5a8 8 0 0 1 0 7M8.5 12a8 8 0 0 1 7 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"4\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"12\" cy=\"20\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"4\" cy=\"12\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"20\" cy=\"12\" r=\"1.2\" fill=\"#0CA678\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-job-level",
    "name": "Job Level",
    "primaryCategory": "hr",
    "keywords": [
      "grade",
      "band",
      "seniority",
      "career",
      "job",
      "level",
      "hr"
    ],
    "aliases": [],
    "description": "Job Level — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"17\" width=\"16\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"12\" width=\"12\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"8\" y=\"7\" width=\"8\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"10\" y=\"3\" width=\"4\" height=\"3\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"17\" width=\"16\" height=\"4\" rx=\"1\" fill=\"#868E96\"/><rect x=\"6\" y=\"12\" width=\"12\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.7\"/><rect x=\"8\" y=\"7\" width=\"8\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"10\" y=\"3\" width=\"4\" height=\"3\" rx=\"1\" fill=\"#F5A623\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-compensation",
    "name": "Compensation",
    "primaryCategory": "hr",
    "keywords": [
      "total",
      "rewards",
      "salary",
      "bonus",
      "equity",
      "compensation",
      "hr"
    ],
    "aliases": [],
    "description": "Compensation — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"10\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5v1M12 15v1M12 16v4M9 21h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9.5 8l2.5 2 2.5-2M9.5 12l2.5-2 2.5 2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"10\" r=\"1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"10\" r=\"5\" fill=\"#F5A623\" fill-opacity=\"0.15\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M9.5 8l2.5 2 2.5-2M9.5 12l2.5-2 2.5 2\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 5v1M12 15v1M12 16v4M9 21h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-id-card",
    "name": "ID Card",
    "primaryCategory": "hr",
    "keywords": [
      "id",
      "card",
      "hr"
    ],
    "aliases": [],
    "description": "ID Card — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"2\" y=\"5\" width=\"20\" height=\"14\" rx=\"2.2\"/><circle cx=\"8.2\" cy=\"12\" r=\"2.4\"/><line x1=\"13\" y1=\"9.7\" x2=\"19\" y2=\"9.7\"/><line x1=\"13\" y1=\"14.3\" x2=\"19\" y2=\"14.3\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-briefcase",
    "name": "Briefcase",
    "primaryCategory": "hr",
    "keywords": [
      "briefcase",
      "hr"
    ],
    "aliases": [],
    "description": "Briefcase — professional human resources and people analytics icon for Power BI dashboards.",
    "recommendedUses": [
      "HR dashboards",
      "Headcount cards",
      "Attrition reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"12.5\" rx=\"2\"/><path d=\"M8.3 8V6.2a2 2 0 0 1 2-2h3.4a2 2 0 0 1 2 2V8\"/><line x1=\"3\" y1=\"13.3\" x2=\"21\" y2=\"13.3\"/>",
    "source": "icon-vault"
  },
]
