// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const LOGISTICS_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-truck",
    "name": "Truck / Shipment",
    "primaryCategory": "logistics",
    "keywords": [
      "delivery",
      "transport",
      "freight",
      "logistics",
      "truck",
      "shipment"
    ],
    "aliases": [],
    "description": "Truck / Shipment — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"2.5\" y=\"8\" width=\"11\" height=\"8\" rx=\"1.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M13.5 11h3.6L20 14v2h-6.5Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"18\" r=\"1.6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"18\" r=\"1.6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"2.5\" y=\"8\" width=\"11\" height=\"8\" rx=\"1.2\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M13.5 11h3.6L20 14v2h-6.5Z\" fill=\"#F08C00\" fill-opacity=\"0.25\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><circle cx=\"7\" cy=\"18\" r=\"1.6\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"18\" r=\"1.6\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-warehouse",
    "name": "Warehouse",
    "primaryCategory": "logistics",
    "keywords": [
      "storage",
      "inventory",
      "facility",
      "logistics",
      "warehouse"
    ],
    "aliases": [],
    "description": "Warehouse — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 10 12 4l9 6v10H3Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 20v-6h6v6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3 10 12 4l9 6v10H3Z\" fill=\"#868E96\" fill-opacity=\"0.16\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M9 20v-6h6v6\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-shipping-box",
    "name": "Shipping Box",
    "primaryCategory": "logistics",
    "keywords": [
      "package",
      "parcel",
      "cargo",
      "logistics",
      "shipping",
      "box"
    ],
    "aliases": [],
    "description": "Shipping Box — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 8 12 4l8.5 4-8.5 4-8.5-4Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 8v8.5L12 20.5l8.5-4V8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 12v8.5\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 8 12 4l8.5 4-8.5 4-8.5-4Z\" fill=\"#F5A623\" fill-opacity=\"0.25\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M3.5 8v8.5L12 20.5l8.5-4V8\" fill=\"#868E96\" fill-opacity=\"0.12\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 12v8.5\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-route",
    "name": "Route / Distribution",
    "primaryCategory": "logistics",
    "keywords": [
      "delivery",
      "path",
      "map",
      "logistics",
      "route",
      "distribution"
    ],
    "aliases": [
      "Delivery Route"
    ],
    "description": "Route / Distribution — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"5.5\" cy=\"6\" r=\"2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"18.5\" cy=\"18\" r=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5.5 8c0 5 8 4 8 9.5\" fill=\"none\" stroke=\"currentColor\" stroke-dasharray=\"2.4 2.2\"/>",
    "multicolorSvg": "<circle cx=\"5.5\" cy=\"6\" r=\"2\" fill=\"#4C6EF5\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"18.5\" cy=\"18\" r=\"2\" fill=\"#0CA678\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M5.5 8c0 5 8 4 8 9.5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-dasharray=\"2.4 2.2\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-container-ship",
    "name": "Container Ship",
    "primaryCategory": "logistics",
    "keywords": [
      "shipping",
      "sea",
      "freight",
      "logistics",
      "container",
      "ship"
    ],
    "aliases": [
      "Cargo Ship"
    ],
    "description": "Container Ship — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 16.5h18l-2 4H5Z\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"9.5\" width=\"4\" height=\"3.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"10.5\" y=\"9.5\" width=\"4\" height=\"3.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 13V6h-2.5l-1.5 3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 13V9.5h11v3.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3 16.5h18l-2 4H5Z\" fill=\"#1C7ED6\" fill-opacity=\"0.2\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"6\" y=\"9.5\" width=\"4\" height=\"3.5\" fill=\"#4C6EF5\" fill-opacity=\"0.4\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><rect x=\"10.5\" y=\"9.5\" width=\"4\" height=\"3.5\" fill=\"#F08C00\" fill-opacity=\"0.4\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M17 13V6h-2.5l-1.5 3\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-pallet",
    "name": "Pallet",
    "primaryCategory": "logistics",
    "keywords": [
      "stock",
      "storage",
      "inventory",
      "logistics",
      "pallet"
    ],
    "aliases": [
      "Pallet Load"
    ],
    "description": "Pallet — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"6\" rx=\"1.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5.5 10v8M12 10v8M18.5 10v8\" stroke=\"currentColor\"/><path d=\"M3 18h18\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"6\" rx=\"1.2\" fill=\"#F5A623\" fill-opacity=\"0.22\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M5.5 10v8M12 10v8M18.5 10v8\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M3 18h18\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-flight",
    "name": "Travel / Flight",
    "primaryCategory": "transportation",
    "keywords": [
      "airplane",
      "travel",
      "flight",
      "transportation"
    ],
    "aliases": [
      "Air Transport",
      "Airplane"
    ],
    "description": "Travel / Flight — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M11 3.5 13 9l6.5 2.6-6 .4-2 4 .5 4.5-2-3-2 3 .5-4.5-6-.4 6.5-2.6Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M11 3.5 13 9l6.5 2.6-6 .4-2 4 .5 4.5-2-3-2 3 .5-4.5-6-.4 6.5-2.6Z\" fill=\"#1C7ED6\" fill-opacity=\"0.22\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-fleet",
    "name": "Fleet / Vehicle",
    "primaryCategory": "transportation",
    "keywords": [
      "vehicle",
      "fleet",
      "car",
      "transportation"
    ],
    "aliases": [],
    "description": "Fleet / Vehicle — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 14 5 8.5h14L20.5 14\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"3\" y=\"14\" width=\"18\" height=\"4.5\" rx=\"1.4\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7.5\" cy=\"18.5\" r=\"1.6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"16.5\" cy=\"18.5\" r=\"1.6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 14 5 8.5h14L20.5 14\" fill=\"#4C6EF5\" fill-opacity=\"0.16\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><rect x=\"3\" y=\"14\" width=\"18\" height=\"4.5\" rx=\"1.4\" fill=\"#4C6EF5\" fill-opacity=\"0.22\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"7.5\" cy=\"18.5\" r=\"1.6\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><circle cx=\"16.5\" cy=\"18.5\" r=\"1.6\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-location-pin",
    "name": "Location",
    "primaryCategory": "transportation",
    "keywords": [
      "map",
      "place",
      "address",
      "location",
      "pin",
      "transportation"
    ],
    "aliases": [
      "Route Pin"
    ],
    "description": "Location — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 21s7-6.5 7-12a7 7 0 1 0-14 0c0 5.5 7 12 7 12Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"9\" r=\"2.4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 21s7-6.5 7-12a7 7 0 1 0-14 0c0 5.5 7 12 7 12Z\" fill=\"#E03131\" fill-opacity=\"0.18\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"9\" r=\"2.4\" fill=\"#E03131\" stroke=\"#E03131\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-forklift",
    "name": "Forklift",
    "primaryCategory": "logistics",
    "keywords": [
      "warehouse",
      "lift",
      "material",
      "handling",
      "forklift",
      "logistics"
    ],
    "aliases": [],
    "description": "Forklift — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"6\" cy=\"18\" r=\"2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"11\" cy=\"18\" r=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 16V8h4l2 4h3v4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 6v12M16 8h3M16 12h3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"6\" cy=\"18\" r=\"2\" fill=\"#2B2D42\" fill-opacity=\"0.2\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><circle cx=\"11\" cy=\"18\" r=\"2\" fill=\"#2B2D42\" fill-opacity=\"0.2\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M4 16V8h4l2 4h3v4\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 6v12M16 8h3M16 12h3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-shipment",
    "name": "Shipment",
    "primaryCategory": "logistics",
    "keywords": [
      "package",
      "delivery",
      "box",
      "ship",
      "shipment",
      "logistics"
    ],
    "aliases": [
      "Software Package",
      "Package"
    ],
    "description": "Shipment — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 20 7v10l-8 4-8-4V7Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 7l8 4 8-4M12 11v10\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 5l8 4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3 20 7v10l-8 4-8-4V7Z\" fill=\"#F08C00\" fill-opacity=\"0.15\"/><path d=\"M12 3 20 7v10l-8 4-8-4V7Z\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 7l8 4 8-4M12 11v10\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-tracking",
    "name": "Order Tracking",
    "primaryCategory": "logistics",
    "keywords": [
      "trace",
      "locate",
      "route",
      "map",
      "tracking",
      "order",
      "logistics"
    ],
    "aliases": [
      "Shipment Tracking"
    ],
    "description": "Order Tracking — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M5 7h6M5 7l2-2M5 7l2 2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 12h9M5 17h5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"15\" r=\"3.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 13.5v1.5l1 1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 7h6M5 7l2-2M5 7l2 2\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 12h9M5 17h5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"17\" cy=\"15\" r=\"3.5\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M17 13.5v1.5l1 1\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-train",
    "name": "Rail Transport",
    "primaryCategory": "transportation",
    "keywords": [
      "metro",
      "railway",
      "commute",
      "train",
      "rail",
      "transport",
      "transportation"
    ],
    "aliases": [],
    "description": "Rail Transport — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"6\" y=\"4\" width=\"12\" height=\"13\" rx=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 11h12\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9\" cy=\"8\" r=\"1.1\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"8\" r=\"1.1\" fill=\"currentColor\"/><path d=\"M8 17l-2 4M16 17l2 4M9 14h6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"6\" y=\"4\" width=\"12\" height=\"13\" rx=\"3\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"6\" y=\"4\" width=\"12\" height=\"13\" rx=\"3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M6 11h12\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"9\" cy=\"8\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"15\" cy=\"8\" r=\"1.2\" fill=\"#0CA678\"/><path d=\"M8 17l-2 4M16 17l2 4\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ev-charge",
    "name": "EV Charging",
    "primaryCategory": "transportation",
    "keywords": [
      "electric",
      "car",
      "green",
      "sustainable",
      "ev",
      "charge",
      "charging",
      "transportation"
    ],
    "aliases": [
      "EV Battery"
    ],
    "description": "EV Charging — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"8\" width=\"11\" height=\"11\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"21\" r=\"1.3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"21\" r=\"1.3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15 11h3v6a1.5 1.5 0 0 1-3 0v-3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 11l-2 3h3l-2 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"8\" width=\"11\" height=\"11\" rx=\"1.5\" fill=\"#0CA678\" fill-opacity=\"0.15\"/><rect x=\"4\" y=\"8\" width=\"11\" height=\"11\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M15 11h3v6a1.5 1.5 0 0 1-3 0v-3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 11l-2 3h3l-2 3\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-last-mile",
    "name": "Last Mile Delivery",
    "primaryCategory": "transportation",
    "keywords": [
      "final",
      "delivery",
      "urban",
      "parcel",
      "last",
      "mile",
      "transportation"
    ],
    "aliases": [],
    "description": "Last Mile Delivery — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M5 12H1l3-3M1 12l3 3\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"5\" y=\"9\" width=\"10\" height=\"6\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"19\" cy=\"15\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15 12v3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 12H1l3-3M1 12l3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"5\" y=\"9\" width=\"10\" height=\"6\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"5\" y=\"9\" width=\"10\" height=\"6\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"19\" cy=\"15\" r=\"2.5\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-port",
    "name": "Seaport",
    "primaryCategory": "transportation",
    "keywords": [
      "shipping",
      "dock",
      "container",
      "vessel",
      "port",
      "seaport",
      "transportation"
    ],
    "aliases": [],
    "description": "Seaport — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 17h18\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 17V9l5-3 5 3v8\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"7\" y=\"12\" width=\"4\" height=\"5\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"11\" width=\"4\" height=\"6\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 9h6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 9l5-3 5 3v8H5Z\" fill=\"#1C7ED6\" fill-opacity=\"0.12\" stroke=\"none\"/><path d=\"M5 9l5-3 5 3v8M3 17h18\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"7\" y=\"12\" width=\"4\" height=\"5\" rx=\"0.5\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><rect x=\"13\" y=\"11\" width=\"4\" height=\"6\" rx=\"0.5\" fill=\"#0CA678\" fill-opacity=\"0.8\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-drone",
    "name": "Drone Delivery",
    "primaryCategory": "transportation",
    "keywords": [
      "uav",
      "autonomous",
      "air",
      "package",
      "drone",
      "delivery",
      "transportation"
    ],
    "aliases": [],
    "description": "Drone Delivery — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"11\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 11H4.5M17.5 11H19M12 8V6.5M7.5 8 6.5 7M16.5 8 17.5 7\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 14l-1 3-2 1M15 14l1 3 2 1M12 14v6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"11\" r=\"3\" fill=\"#7048E8\" fill-opacity=\"0.2\" stroke=\"#7048E8\" stroke-width=\"1.6\"/><path d=\"M6 11H4.5M17.5 11H19M12 8V6.5M7.5 8 6.5 7M16.5 8 17.5 7\" fill=\"none\" stroke=\"#7048E8\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 14l-1 3M15 14l1 3M12 14v6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-cold-chain",
    "name": "Cold Chain",
    "primaryCategory": "transportation",
    "keywords": [
      "refrigerated",
      "temperature",
      "fresh",
      "pharma",
      "cold",
      "chain",
      "transportation"
    ],
    "aliases": [],
    "description": "Cold Chain — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"8\" width=\"12\" height=\"12\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12h12\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 10h5l-2-2M21 10l-2 2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 8V6M12 8V6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"6\" r=\"1\" fill=\"#1C7ED6\"/><circle cx=\"12\" cy=\"6\" r=\"1\" fill=\"#1C7ED6\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"8\" width=\"12\" height=\"12\" rx=\"1.5\" fill=\"#1C7ED6\" fill-opacity=\"0.12\"/><rect x=\"4\" y=\"8\" width=\"12\" height=\"12\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M4 12h12\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 10h5l-2-2M21 10l-2 2\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-customs",
    "name": "Customs Clearance",
    "primaryCategory": "transportation",
    "keywords": [
      "import",
      "export",
      "duty",
      "border",
      "customs",
      "clearance",
      "transportation"
    ],
    "aliases": [],
    "description": "Customs Clearance — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 10H20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"15\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10.5 14.5l1.5 1.5 3-3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"5\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"15\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M10.5 14.5l1.5 1.5 3-3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-freight",
    "name": "Freight",
    "primaryCategory": "transportation",
    "keywords": [
      "cargo",
      "rate",
      "shipping",
      "cost",
      "ton",
      "freight",
      "transportation"
    ],
    "aliases": [],
    "description": "Freight — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"11\" height=\"7\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M14 11h4l3 3v1h-7\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"17\" r=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"17\" r=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 15h2M9 15h6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"8\" width=\"11\" height=\"7\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><path d=\"M14 11h4l3 3v1h-7\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"7\" cy=\"17\" r=\"1.8\" fill=\"#2B2D42\" fill-opacity=\"0.3\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"17\" r=\"1.8\" fill=\"#2B2D42\" fill-opacity=\"0.3\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-gps-tracking",
    "name": "GPS Tracking",
    "primaryCategory": "transportation",
    "keywords": [
      "location",
      "vehicle",
      "fleet",
      "telematics",
      "gps",
      "tracking",
      "transportation"
    ],
    "aliases": [],
    "description": "GPS Tracking — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3C8.7 3 6 5.7 6 9c0 5.2 6 12 6 12s6-6.8 6-12c0-3.3-2.7-6-6-6Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"9\" r=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 9H6M18 9h3M12 3V0M12 21v3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3C8.7 3 6 5.7 6 9c0 5.2 6 12 6 12s6-6.8 6-12c0-3.3-2.7-6-6-6Z\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"none\"/><path d=\"M12 3C8.7 3 6 5.7 6 9c0 5.2 6 12 6 12s6-6.8 6-12c0-3.3-2.7-6-6-6Z\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"9\" r=\"2.2\" fill=\"#0CA678\"/><path d=\"M3 9H6M18 9h3M12 3V0M12 21v3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-logistics-cost",
    "name": "Logistics Cost",
    "primaryCategory": "transportation",
    "keywords": [
      "spend",
      "freight",
      "handling",
      "budget",
      "logistics",
      "cost",
      "transportation"
    ],
    "aliases": [],
    "description": "Logistics Cost — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 9l6 6M15 9l-6 6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5v2M20.5 12H19\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#F5A623\" fill-opacity=\"0.1\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"#F5A623\" fill-opacity=\"0.2\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M9 9l6 6M15 9l-6 6\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-intermodal",
    "name": "Intermodal",
    "primaryCategory": "transportation",
    "keywords": [
      "multi",
      "modal",
      "ship",
      "rail",
      "truck",
      "combine",
      "intermodal",
      "transportation"
    ],
    "aliases": [],
    "description": "Intermodal — professional transportation and fleet icon for Power BI dashboards.",
    "recommendedUses": [
      "Fleet dashboards",
      "Route reports",
      "Delivery KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"14\" width=\"5\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"9.5\" y=\"14\" width=\"5\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"5\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5.5 14V11l4-4 4 4v3M16.5 14V12l-3-4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5.5 11h4M12 11h4.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"14\" width=\"5\" height=\"5\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"9.5\" y=\"14\" width=\"5\" height=\"5\" rx=\"1\" fill=\"#1C7ED6\"/><rect x=\"16\" y=\"14\" width=\"5\" height=\"5\" rx=\"1\" fill=\"#F08C00\"/><path d=\"M5.5 14V11l4-4 4 4v3M16.5 14V12l-3-4\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-bol",
    "name": "Bill of Lading",
    "primaryCategory": "logistics",
    "keywords": [
      "shipping",
      "document",
      "cargo",
      "consignment",
      "bol",
      "bill",
      "of",
      "lading",
      "logistics"
    ],
    "aliases": [],
    "description": "Bill of Lading — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 7h8M8 10h8M8 13h5M8 16h3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 3h14v18H5Z\" fill=\"#1C7ED6\" fill-opacity=\"0.08\" stroke=\"none\"/><rect x=\"5\" y=\"3\" width=\"14\" height=\"18\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 7h8M8 10h8M8 13h5M8 16h3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-dwell-time",
    "name": "Dwell Time",
    "primaryCategory": "logistics",
    "keywords": [
      "delay",
      "port",
      "yard",
      "wait",
      "duration",
      "dwell",
      "time",
      "logistics"
    ],
    "aliases": [],
    "description": "Dwell Time — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7v5l4 2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5v1M20.5 12H19M3.5 12H5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#F08C00\" fill-opacity=\"0.1\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M12 7v5l4 2\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 3.5v1M20.5 12H19M3.5 12H5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-3pl",
    "name": "3PL",
    "primaryCategory": "logistics",
    "keywords": [
      "third",
      "party",
      "logistics",
      "outsource",
      "provider",
      "3pl"
    ],
    "aliases": [],
    "description": "3PL — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"10\" width=\"7\" height=\"9\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"6\" width=\"7\" height=\"13\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 14.5h4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6.5 10V8l4-4 4 4v2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"10\" width=\"7\" height=\"9\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><rect x=\"14\" y=\"6\" width=\"7\" height=\"13\" rx=\"1.5\" fill=\"#0CA678\" fill-opacity=\"0.8\"/><path d=\"M10 14.5h4\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-cross-dock",
    "name": "Cross Docking",
    "primaryCategory": "logistics",
    "keywords": [
      "transfer",
      "direct",
      "flow",
      "no",
      "storage",
      "cross",
      "dock",
      "docking",
      "logistics"
    ],
    "aliases": [],
    "description": "Cross Docking — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 10h4M10 14h4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 10l2 2-2 2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M13 10l-2 2 2 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"#1C7ED6\" fill-opacity=\"0.12\"/><rect x=\"14\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"#0CA678\" fill-opacity=\"0.12\"/><rect x=\"3\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"14\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M10 10h4M10 14h4\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-just-in-time",
    "name": "Just In Time",
    "primaryCategory": "logistics",
    "keywords": [
      "jit",
      "lean",
      "pull",
      "inventory",
      "zero",
      "just",
      "in",
      "time",
      "logistics"
    ],
    "aliases": [],
    "description": "Just In Time — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7v5l-3 3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.1\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M12 7v5l-3 3\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-fulfillment",
    "name": "Fulfillment",
    "primaryCategory": "logistics",
    "keywords": [
      "pick",
      "pack",
      "ship",
      "order",
      "complete",
      "fulfillment",
      "logistics"
    ],
    "aliases": [
      "Order Fulfilled"
    ],
    "description": "Fulfillment — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"5\" y=\"10\" width=\"14\" height=\"10\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 10 12 5 19 10\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 15l2 2 6-6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5v5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 10 12 5 19 10v10H5Z\" fill=\"#0CA678\" fill-opacity=\"0.1\" stroke=\"none\"/><path d=\"M5 10 12 5 19 10\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"5\" y=\"10\" width=\"14\" height=\"10\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 15l2 2 6-6\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-shipping-container",
    "name": "Shipping Container",
    "primaryCategory": "logistics",
    "keywords": [
      "shipping",
      "container",
      "logistics"
    ],
    "aliases": [],
    "description": "Shipping Container — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"2\" y=\"7\" width=\"20\" height=\"11\" rx=\"1\"/><line x1=\"2\" y1=\"12.5\" x2=\"22\" y2=\"12.5\"/><line x1=\"7\" y1=\"7\" x2=\"7\" y2=\"18\"/><line x1=\"12\" y1=\"7\" x2=\"12\" y2=\"18\"/><line x1=\"17\" y1=\"7\" x2=\"17\" y2=\"18\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-crane-port",
    "name": "Port Crane",
    "primaryCategory": "logistics",
    "keywords": [
      "crane",
      "port",
      "logistics"
    ],
    "aliases": [],
    "description": "Port Crane — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<line x1=\"4\" y1=\"21\" x2=\"4\" y2=\"6\"/><line x1=\"4\" y1=\"6\" x2=\"18\" y2=\"6\"/><line x1=\"14\" y1=\"6\" x2=\"14\" y2=\"3\"/><line x1=\"18\" y1=\"6\" x2=\"18\" y2=\"11\"/><rect x=\"15\" y=\"11\" width=\"6\" height=\"4\"/><line x1=\"4\" y1=\"12\" x2=\"9\" y2=\"12\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-package-scan",
    "name": "Package Scan",
    "primaryCategory": "logistics",
    "keywords": [
      "package",
      "scan",
      "logistics"
    ],
    "aliases": [],
    "description": "Package Scan — professional supply chain and logistics icon for Power BI dashboards.",
    "recommendedUses": [
      "Logistics dashboards",
      "Shipment trackers",
      "OTIF scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"6\" width=\"16\" height=\"12\" rx=\"1.5\"/><path d=\"M4 6l8 5 8-5\"/><line x1=\"2\" y1=\"3\" x2=\"2\" y2=\"7\"/><line x1=\"22\" y1=\"3\" x2=\"22\" y2=\"7\"/><line x1=\"2\" y1=\"3\" x2=\"6\" y2=\"3\"/><line x1=\"18\" y1=\"3\" x2=\"22\" y2=\"3\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-boarding-pass",
    "name": "Boarding Pass",
    "primaryCategory": "travel",
    "keywords": [
      "boarding",
      "pass",
      "travel"
    ],
    "aliases": [],
    "description": "Boarding Pass — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 6h18v9H9l-3 3v-3H3V6Z\"/><line x1=\"6\" y1=\"9.5\" x2=\"15\" y2=\"9.5\"/><line x1=\"6\" y1=\"12.5\" x2=\"12\" y2=\"12.5\"/><circle cx=\"18\" cy=\"9.5\" r=\"1.3\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-suitcase",
    "name": "Suitcase",
    "primaryCategory": "travel",
    "keywords": [
      "suitcase",
      "travel"
    ],
    "aliases": [],
    "description": "Suitcase — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"12\" rx=\"2\"/><path d=\"M9 8V5.5a1.5 1.5 0 0 1 1.5-1.5h3A1.5 1.5 0 0 1 15 5.5V8\"/><line x1=\"3\" y1=\"13.5\" x2=\"21\" y2=\"13.5\"/><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"20\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-control-tower",
    "name": "Airport Tower",
    "primaryCategory": "travel",
    "keywords": [
      "control",
      "tower",
      "airport",
      "travel"
    ],
    "aliases": [],
    "description": "Airport Tower — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M9 21V11l3-7 3 7v10\"/><line x1=\"7\" y1=\"21\" x2=\"17\" y2=\"21\"/><line x1=\"8.5\" y1=\"14\" x2=\"15.5\" y2=\"14\"/><line x1=\"10.5\" y1=\"7\" x2=\"13.5\" y2=\"7\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-passport",
    "name": "Passport",
    "primaryCategory": "travel",
    "keywords": [
      "passport",
      "travel"
    ],
    "aliases": [],
    "description": "Passport — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"5\" y=\"2\" width=\"14\" height=\"20\" rx=\"1.5\"/><circle cx=\"12\" cy=\"9\" r=\"3\"/><line x1=\"8\" y1=\"16\" x2=\"16\" y2=\"16\"/><line x1=\"8\" y1=\"18.5\" x2=\"16\" y2=\"18.5\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-luggage-tag",
    "name": "Luggage Tag",
    "primaryCategory": "travel",
    "keywords": [
      "luggage",
      "tag",
      "travel"
    ],
    "aliases": [],
    "description": "Luggage Tag — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M13 3l8 8-9 9-8-8a2 2 0 0 1 0-2.8L11 2.3a2 2 0 0 1 2 .7Z\"/><circle cx=\"9\" cy=\"9\" r=\"1.6\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-flight-path",
    "name": "Flight Path",
    "primaryCategory": "travel",
    "keywords": [
      "flight",
      "path",
      "travel"
    ],
    "aliases": [],
    "description": "Flight Path — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3 19c5-9 7-15 9-15s4 6 9 15\"/><circle cx=\"12\" cy=\"4\" r=\"1.3\" fill=\"currentColor\" stroke=\"none\"/><path d=\"M9 15l3 4 3-4\"/>",
    "source": "icon-vault"
  },
  {
    "id": "v2-check-in-desk",
    "name": "Check-in Desk",
    "primaryCategory": "travel",
    "keywords": [
      "check",
      "in",
      "desk",
      "travel"
    ],
    "aliases": [],
    "description": "Check-in Desk — professional airline and travel icon for Power BI dashboards.",
    "recommendedUses": [
      "Travel dashboards",
      "Route maps",
      "Load-factor KPIs"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"2\" y=\"13\" width=\"20\" height=\"7\" rx=\"1\"/><line x1=\"4\" y1=\"13\" x2=\"4\" y2=\"9\"/><line x1=\"4\" y1=\"9\" x2=\"20\" y2=\"9\"/><line x1=\"20\" y1=\"9\" x2=\"20\" y2=\"13\"/><circle cx=\"12\" cy=\"16.3\" r=\"0.8\" fill=\"currentColor\" stroke=\"none\"/>",
    "source": "icon-vault"
  },
]
