// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const PROJECT_MANAGEMENT_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-project-timeline",
    "name": "Project Timeline",
    "primaryCategory": "project",
    "keywords": [
      "gantt",
      "schedule",
      "plan",
      "project",
      "timeline"
    ],
    "aliases": [],
    "description": "Project Timeline — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 6h7M3.5 12h12M3.5 18h5\" stroke=\"currentColor\"/><circle cx=\"13\" cy=\"6\" r=\"1.4\" fill=\"currentColor\"/><circle cx=\"18\" cy=\"12\" r=\"1.4\" fill=\"currentColor\"/><circle cx=\"10.5\" cy=\"18\" r=\"1.4\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 6h7\" stroke=\"#4C6EF5\" stroke-width=\"2.2\" stroke-linecap=\"round\"/><path d=\"M3.5 12h12\" stroke=\"#0CA678\" stroke-width=\"2.2\" stroke-linecap=\"round\"/><path d=\"M3.5 18h5\" stroke=\"#F08C00\" stroke-width=\"2.2\" stroke-linecap=\"round\"/><circle cx=\"13\" cy=\"6\" r=\"1.4\" fill=\"#4C6EF5\"/><circle cx=\"18\" cy=\"12\" r=\"1.4\" fill=\"#0CA678\"/><circle cx=\"10.5\" cy=\"18\" r=\"1.4\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-task",
    "name": "Task",
    "primaryCategory": "project",
    "keywords": [
      "to-do",
      "checklist",
      "action",
      "item",
      "project",
      "task"
    ],
    "aliases": [
      "Checklist"
    ],
    "description": "Task — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"3.5\" width=\"16\" height=\"17\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9.5h8M8 13h8M8 16.5h5\" stroke=\"currentColor\"/><circle cx=\"6.2\" cy=\"9.5\" r=\"0.5\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"3.5\" width=\"16\" height=\"17\" rx=\"2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M8 9.5h8\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M8 13h8\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M8 16.5h5\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-kanban",
    "name": "Kanban Board",
    "primaryCategory": "project",
    "keywords": [
      "board",
      "sprint",
      "agile",
      "project",
      "kanban"
    ],
    "aliases": [],
    "description": "Kanban Board — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 4v16M15 4v16\" stroke=\"currentColor\"/><rect x=\"4.3\" y=\"6\" width=\"3.4\" height=\"4\" rx=\"0.6\" fill=\"currentColor\"/><rect x=\"10.3\" y=\"6\" width=\"3.4\" height=\"6.5\" rx=\"0.6\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"1.8\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M9 4v16M15 4v16\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><rect x=\"4.3\" y=\"6\" width=\"3.4\" height=\"4\" rx=\"0.6\" fill=\"#E03131\" fill-opacity=\"0.5\"/><rect x=\"10.3\" y=\"6\" width=\"3.4\" height=\"6.5\" rx=\"0.6\" fill=\"#F08C00\" fill-opacity=\"0.5\"/><rect x=\"16.3\" y=\"6\" width=\"3.4\" height=\"3\" rx=\"0.6\" fill=\"#0CA678\" fill-opacity=\"0.5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-priority",
    "name": "Priority",
    "primaryCategory": "project",
    "keywords": [
      "urgent",
      "important",
      "flag",
      "project",
      "priority"
    ],
    "aliases": [],
    "description": "Priority — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 3v18\" stroke=\"currentColor\"/><path d=\"M6 4.5h12l-3 3.5 3 3.5H6Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 3v18\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M6 4.5h12l-3 3.5 3 3.5H6Z\" fill=\"#E03131\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-collaboration",
    "name": "Collaboration",
    "primaryCategory": "project",
    "keywords": [
      "teamwork",
      "shared",
      "project",
      "people",
      "collaboration"
    ],
    "aliases": [],
    "description": "Collaboration — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"8\" cy=\"9\" r=\"2.6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"16\" cy=\"9\" r=\"2.6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 19c0-2.9 2-5.1 4.5-5.1M19.5 19c0-2.9-2-5.1-4.5-5.1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 13.5v6\" stroke=\"currentColor\" stroke-dasharray=\"2 2\"/>",
    "multicolorSvg": "<circle cx=\"8\" cy=\"9\" r=\"2.6\" fill=\"#4C6EF5\" fill-opacity=\"0.3\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"16\" cy=\"9\" r=\"2.6\" fill=\"#0CA678\" fill-opacity=\"0.3\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M3.5 19c0-2.9 2-5.1 4.5-5.1M19.5 19c0-2.9-2-5.1-4.5-5.1\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-resource-allocation",
    "name": "Resource Allocation",
    "primaryCategory": "project",
    "keywords": [
      "assignment",
      "capacity",
      "planning",
      "project",
      "resource",
      "allocation"
    ],
    "aliases": [],
    "description": "Resource Allocation — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"6.5\" r=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"6.5\" r=\"2.2\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"9.5\" y=\"14\" width=\"5\" height=\"6\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 8.7v3.3l5 2M17 8.7v3.3l-5 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"6.5\" r=\"2.2\" fill=\"#4C6EF5\" fill-opacity=\"0.3\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"6.5\" r=\"2.2\" fill=\"#0CA678\" fill-opacity=\"0.3\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><rect x=\"9.5\" y=\"14\" width=\"5\" height=\"6\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.25\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M7 8.7v3.3l5 2M17 8.7v3.3l-5 2\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-gantt",
    "name": "Gantt Chart",
    "primaryCategory": "project",
    "keywords": [
      "timeline",
      "schedule",
      "plan",
      "bars",
      "gantt",
      "chart",
      "project"
    ],
    "aliases": [],
    "description": "Gantt Chart — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"7\" y=\"6\" width=\"8\" height=\"2\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"10\" y=\"10\" width=\"7\" height=\"2\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"6\" y=\"14\" width=\"6\" height=\"2\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"7\" y=\"6\" width=\"8\" height=\"2\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"10\" y=\"10\" width=\"7\" height=\"2\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"6\" y=\"14\" width=\"6\" height=\"2\" rx=\"1\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-sprint",
    "name": "Sprint",
    "primaryCategory": "project",
    "keywords": [
      "agile",
      "iteration",
      "cycle",
      "run",
      "sprint",
      "project"
    ],
    "aliases": [],
    "description": "Sprint — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 12 12 6M12 12l4 3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M19 8l1.5-1M5 8 3.5 7\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"#4C6EF5\" fill-opacity=\"0.1\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 12 12 6M12 12l4 3\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\" fill=\"#E03131\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-dependency",
    "name": "Dependency",
    "primaryCategory": "project",
    "keywords": [
      "link",
      "blocked",
      "relation",
      "chain",
      "dependency",
      "project"
    ],
    "aliases": [],
    "description": "Dependency — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"7\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"17\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9.2 9.2 14.8 14.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 7h2M12 17h2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"7\" r=\"3\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"17\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M9.2 9.2 14.8 14.8\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-whiteboard",
    "name": "Whiteboard",
    "primaryCategory": "project",
    "keywords": [
      "brainstorm",
      "collaborate",
      "plan",
      "whiteboard",
      "project"
    ],
    "aliases": [],
    "description": "Whiteboard — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 16v3M9 21h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 8h5M6 11h8M15 8l2 2-3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.08\"/><rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M12 16v3M9 21h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 8h5M6 11h8\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 8l2 2-3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-video-call",
    "name": "Video Meeting",
    "primaryCategory": "project",
    "keywords": [
      "conference",
      "remote",
      "zoom",
      "video",
      "call",
      "meeting",
      "project"
    ],
    "aliases": [],
    "description": "Video Meeting — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"7\" width=\"12\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15 11l5-3v8l-5-3Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"11\" r=\"0\" fill=\"currentColor\"/><path d=\"M6 13h4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"7\" width=\"12\" height=\"10\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.15\"/><rect x=\"3\" y=\"7\" width=\"12\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M15 11l5-3v8l-5-3Z\" fill=\"#0CA678\" fill-opacity=\"0.4\"/><path d=\"M15 11l5-3v8l-5-3Z\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-vision",
    "name": "Vision",
    "primaryCategory": "strategy",
    "keywords": [
      "direction",
      "future",
      "goal",
      "ambition",
      "vision",
      "strategy"
    ],
    "aliases": [],
    "description": "Vision — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#4C6EF5\" fill-opacity=\"0.1\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12Z\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.3\" stroke=\"#0CA678\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-mission",
    "name": "Mission",
    "primaryCategory": "strategy",
    "keywords": [
      "purpose",
      "goal",
      "statement",
      "objective",
      "mission",
      "strategy"
    ],
    "aliases": [],
    "description": "Mission — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 4 7v5c0 4.5 3.5 8 8 9 4.5-1 8-4.5 8-9V7Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 12l2 2 4-4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3 4 7v5c0 4.5 3.5 8 8 9 4.5-1 8-4.5 8-9V7Z\" fill=\"#4C6EF5\" fill-opacity=\"0.12\" stroke=\"none\"/><path d=\"M12 3 4 7v5c0 4.5 3.5 8 8 9 4.5-1 8-4.5 8-9V7Z\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 12l2 2 4-4\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-swot",
    "name": "SWOT Analysis",
    "primaryCategory": "strategy",
    "keywords": [
      "strength",
      "weakness",
      "opportunity",
      "threat",
      "swot",
      "analysis",
      "strategy"
    ],
    "aliases": [],
    "description": "SWOT Analysis — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"7\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"7\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"4\" y=\"13\" width=\"7\" height=\"7\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"13\" y=\"13\" width=\"7\" height=\"7\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12h16M12 4v16\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"7\" height=\"7\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.8\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"7\" rx=\"1\" fill=\"#4C6EF5\" fill-opacity=\"0.8\"/><rect x=\"4\" y=\"13\" width=\"7\" height=\"7\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.8\"/><rect x=\"13\" y=\"13\" width=\"7\" height=\"7\" rx=\"1\" fill=\"#E03131\" fill-opacity=\"0.8\"/><path d=\"M4 12h16M12 4v16\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-okr",
    "name": "OKR",
    "primaryCategory": "strategy",
    "keywords": [
      "objective",
      "key",
      "result",
      "goal",
      "align",
      "okr",
      "strategy"
    ],
    "aliases": [
      "Strategy Execution",
      "Execution"
    ],
    "description": "OKR — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#868E96\" fill-opacity=\"0.1\" stroke=\"#868E96\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"2\" fill=\"#E03131\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\" fill=\"#E03131\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-roadmap",
    "name": "Roadmap",
    "primaryCategory": "strategy",
    "keywords": [
      "plan",
      "phase",
      "timeline",
      "milestones",
      "roadmap",
      "strategy"
    ],
    "aliases": [],
    "description": "Roadmap — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 12H20M4 12l4-4M4 12l4 4\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"7\" y=\"7\" width=\"3\" height=\"3\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"12\" y=\"9\" width=\"3\" height=\"3\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"17\" y=\"7\" width=\"3\" height=\"3\" rx=\"0.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 10v2M12 12v3M17 10v2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 12H20M4 12l4-4M4 12l4 4\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"7\" y=\"7\" width=\"3\" height=\"3\" rx=\"0.5\" fill=\"#0CA678\"/><rect x=\"12\" y=\"9\" width=\"3\" height=\"3\" rx=\"0.5\" fill=\"#F08C00\"/><rect x=\"17\" y=\"7\" width=\"3\" height=\"3\" rx=\"0.5\" fill=\"#4C6EF5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-competitive-analysis",
    "name": "Competitive Analysis",
    "primaryCategory": "strategy",
    "keywords": [
      "benchmark",
      "compare",
      "rival",
      "market",
      "competitive",
      "analysis",
      "strategy"
    ],
    "aliases": [],
    "description": "Competitive Analysis — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H20M12 4V20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"7\" r=\"1.5\" fill=\"#4C6EF5\"/><circle cx=\"16\" cy=\"8\" r=\"1.5\" fill=\"#E03131\"/><circle cx=\"9\" cy=\"14\" r=\"1.5\" fill=\"#0CA678\"/><circle cx=\"16\" cy=\"15\" r=\"1.5\" fill=\"#F08C00\"/><circle cx=\"12\" cy=\"10\" r=\"1.2\" fill=\"#4C6EF5\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"#868E96\" fill-opacity=\"0.06\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M4 12H20M12 4V20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"7\" cy=\"7\" r=\"1.6\" fill=\"#4C6EF5\"/><circle cx=\"16\" cy=\"8\" r=\"1.6\" fill=\"#E03131\"/><circle cx=\"9\" cy=\"14\" r=\"1.6\" fill=\"#0CA678\"/><circle cx=\"16\" cy=\"15\" r=\"1.6\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-market-sizing",
    "name": "Market Sizing",
    "primaryCategory": "strategy",
    "keywords": [
      "tam",
      "sam",
      "som",
      "addressable",
      "market",
      "sizing",
      "strategy"
    ],
    "aliases": [],
    "description": "Market Sizing — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"5.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M20.5 12H12M12 3.5v17\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#868E96\" fill-opacity=\"0.1\" stroke=\"#868E96\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"5.5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.4\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M20.5 12H12M12 3.5v17\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-scenario-planning",
    "name": "Scenario Planning",
    "primaryCategory": "strategy",
    "keywords": [
      "what-if",
      "forecast",
      "alternate",
      "path",
      "scenario",
      "planning",
      "strategy"
    ],
    "aliases": [],
    "description": "Scenario Planning — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 18 8 12 11 14 14 8 17 10 20 6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 18 8 14 11 16 14 12 17 14 20 11\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 18 8 12 11 14 14 8 17 10 20 6\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 18 8 14 11 16 14 12 17 14 20 11\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-decision-tree",
    "name": "Decision Tree",
    "primaryCategory": "strategy",
    "keywords": [
      "branch",
      "option",
      "if-else",
      "outcome",
      "decision",
      "tree",
      "strategy"
    ],
    "aliases": [],
    "description": "Decision Tree — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"5\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"6\" cy=\"13\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"18\" cy=\"13\" r=\"2.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"4\" cy=\"20\" r=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9\" cy=\"20\" r=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"15\" cy=\"20\" r=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"21\" cy=\"20\" r=\"1.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7.5v3M12 10.5l-6 2M12 10.5l6 2M6 15.5l-2 3M6 15.5l3 3M18 15.5l-3 3M18 15.5l3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"5\" r=\"2.5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"6\" cy=\"13\" r=\"2.5\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><circle cx=\"18\" cy=\"13\" r=\"2.5\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M12 7.5v3M12 10.5l-6 2M12 10.5l6 2M6 15.5l-2 3M6 15.5l3 3M18 15.5l-3 3M18 15.5l3 3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-innovation",
    "name": "Innovation",
    "primaryCategory": "strategy",
    "keywords": [
      "idea",
      "lightbulb",
      "new",
      "create",
      "invent",
      "innovation",
      "strategy"
    ],
    "aliases": [
      "Idea"
    ],
    "description": "Innovation — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M9 18h6M9 21h6M12 3a6 6 0 0 1 4.5 10L15 18H9L7.5 13A6 6 0 0 1 12 3Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7v4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M9 18h6M9 21h6M12 3a6 6 0 0 1 4.5 10L15 18H9L7.5 13A6 6 0 0 1 12 3Z\" fill=\"#F5A623\" fill-opacity=\"0.15\" stroke=\"none\"/><path d=\"M9 18h6M9 21h6M12 3a6 6 0 0 1 4.5 10L15 18H9L7.5 13A6 6 0 0 1 12 3Z\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 7v4\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-risk-matrix",
    "name": "Risk Matrix",
    "primaryCategory": "strategy",
    "keywords": [
      "impact",
      "probability",
      "heat",
      "map",
      "assess",
      "risk",
      "matrix",
      "strategy"
    ],
    "aliases": [],
    "description": "Risk Matrix — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H20M12 4V20\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"7\" r=\"1.4\" fill=\"#E03131\"/><circle cx=\"16\" cy=\"7\" r=\"1.4\" fill=\"#F08C00\"/><circle cx=\"7\" cy=\"15\" r=\"1.4\" fill=\"#0CA678\"/><circle cx=\"14\" cy=\"10\" r=\"1.4\" fill=\"#F08C00\"/><circle cx=\"10\" cy=\"14\" r=\"1.4\" fill=\"#0CA678\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#E03131\" fill-opacity=\"0.15\"/><rect x=\"12\" y=\"4\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#F08C00\" fill-opacity=\"0.15\"/><rect x=\"4\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#0CA678\" fill-opacity=\"0.15\"/><rect x=\"12\" y=\"12\" width=\"8\" height=\"8\" rx=\"1\" fill=\"#868E96\" fill-opacity=\"0.1\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M4 12H20M12 4V20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-business-model",
    "name": "Business Model",
    "primaryCategory": "strategy",
    "keywords": [
      "canvas",
      "value",
      "proposition",
      "revenue",
      "business",
      "model",
      "strategy"
    ],
    "aliases": [],
    "description": "Business Model — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 10h18M3 14h18M8 4v16M13 4v16\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3 4h5v6H3Z\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"none\"/><path d=\"M8 4h5v6H8Z\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"none\"/><path d=\"M13 4h8v6h-8Z\" fill=\"#F08C00\" fill-opacity=\"0.2\" stroke=\"none\"/><path d=\"M3 10h18v10H3Z\" fill=\"#868E96\" fill-opacity=\"0.08\" stroke=\"none\"/><rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M3 10h18M3 14h18M8 4v16M13 4v16\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-portfolio-mgmt",
    "name": "Portfolio Management",
    "primaryCategory": "strategy",
    "keywords": [
      "projects",
      "prioritize",
      "resource",
      "balance",
      "portfolio",
      "mgmt",
      "management",
      "strategy"
    ],
    "aliases": [],
    "description": "Portfolio Management — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5A8.5 8.5 0 0 1 20.5 12H12Z\" fill=\"#4C6EF5\" fill-opacity=\"0.8\" stroke=\"none\"/><path d=\"M12 3.5A8.5 8.5 0 0 0 3.5 12H12Z\" fill=\"#0CA678\" fill-opacity=\"0.8\" stroke=\"none\"/><path d=\"M3.5 12A8.5 8.5 0 0 0 12 20.5V12Z\" fill=\"#F08C00\" fill-opacity=\"0.8\" stroke=\"none\"/><path d=\"M12 12h8.5A8.5 8.5 0 0 1 12 20.5Z\" fill=\"#F5A623\" fill-opacity=\"0.8\" stroke=\"none\"/><circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M12 3.5A8.5 8.5 0 0 1 20.5 12H12Z\" fill=\"#4C6EF5\" fill-opacity=\"0.9\" stroke=\"none\"/><path d=\"M12 3.5A8.5 8.5 0 0 0 3.5 12H12Z\" fill=\"#0CA678\" fill-opacity=\"0.9\" stroke=\"none\"/><path d=\"M3.5 12A8.5 8.5 0 0 0 12 20.5V12Z\" fill=\"#F08C00\" fill-opacity=\"0.9\" stroke=\"none\"/><path d=\"M12 12h8.5A8.5 8.5 0 0 1 12 20.5Z\" fill=\"#F5A623\" fill-opacity=\"0.9\" stroke=\"none\"/><circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-merger",
    "name": "Merger & Acquisition",
    "primaryCategory": "strategy",
    "keywords": [
      "m&a",
      "deal",
      "integration",
      "combine",
      "merger",
      "acquisition",
      "strategy"
    ],
    "aliases": [],
    "description": "Merger & Acquisition — professional strategy and planning icon for Power BI dashboards.",
    "recommendedUses": [
      "Executive dashboards",
      "OKR scorecards",
      "Board decks"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"12\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"12\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 12A5 5 0 0 1 12 7\" fill=\"#4C6EF5\" fill-opacity=\"0.3\" stroke=\"none\"/><path d=\"M17 12A5 5 0 0 0 12 7\" fill=\"#0CA678\" fill-opacity=\"0.3\" stroke=\"none\"/><path d=\"M12 7v10\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"12\" r=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"12\" r=\"5\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M7 12A5 5 0 0 1 12 7\" fill=\"#4C6EF5\" fill-opacity=\"0.4\" stroke=\"none\"/><path d=\"M17 12A5 5 0 0 0 12 7\" fill=\"#0CA678\" fill-opacity=\"0.4\" stroke=\"none\"/><path d=\"M12 7v10\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-risk-management",
    "name": "Risk Management",
    "primaryCategory": "project",
    "keywords": [
      "issue",
      "mitigation",
      "probability",
      "impact",
      "risk",
      "management",
      "project"
    ],
    "aliases": [],
    "description": "Risk Management — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 21 20H3Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 9v5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"17.5\" r=\"1.2\" fill=\"#F08C00\"/><path d=\"M12 3 21 20H3Z\" fill=\"#F08C00\" fill-opacity=\"0.12\" stroke=\"none\"/>",
    "multicolorSvg": "<path d=\"M12 3 21 20H3Z\" fill=\"#F08C00\" fill-opacity=\"0.15\" stroke=\"none\"/><path d=\"M12 3 21 20H3Z\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 9v5\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"17.5\" r=\"1.3\" fill=\"#fff\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-stakeholder",
    "name": "Stakeholder",
    "primaryCategory": "project",
    "keywords": [
      "communicate",
      "engage",
      "map",
      "interest",
      "power",
      "stakeholder",
      "project"
    ],
    "aliases": [],
    "description": "Stakeholder — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"7\" cy=\"7\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"7\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"16\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 10v2l5 4 5-4v-2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"20\" r=\"1\" fill=\"#4C6EF5\"/>",
    "multicolorSvg": "<circle cx=\"7\" cy=\"7\" r=\"3\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"17\" cy=\"7\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"16\" r=\"3\" fill=\"#F08C00\" fill-opacity=\"0.2\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M7 10v2l5 4 5-4v-2\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-change-mgmt",
    "name": "Change Management",
    "primaryCategory": "project",
    "keywords": [
      "transform",
      "adapt",
      "process",
      "people",
      "change",
      "mgmt",
      "management",
      "project"
    ],
    "aliases": [],
    "description": "Change Management — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"7\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5v2M12 17v2M5 12H7M17 12h2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 19a7 7 0 0 0 0-14\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5l3 3-3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"7\" fill=\"#7048E8\" fill-opacity=\"0.1\" stroke=\"#7048E8\" stroke-width=\"1.6\"/><path d=\"M12 19a7 7 0 0 0 0-14\" fill=\"none\" stroke=\"#7048E8\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 5l3 3-3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-lessons-learned",
    "name": "Lessons Learned",
    "primaryCategory": "project",
    "keywords": [
      "retrospective",
      "review",
      "improve",
      "action",
      "lessons",
      "learned",
      "project"
    ],
    "aliases": [],
    "description": "Lessons Learned — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 9h10M7 12h10M7 15h6\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"17\" cy=\"15\" r=\"1.1\" fill=\"#0CA678\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.06\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 9h10M7 12h10M7 15h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"17\" cy=\"15\" r=\"1.2\" fill=\"#0CA678\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-burndown",
    "name": "Burndown Chart",
    "primaryCategory": "project",
    "keywords": [
      "scrum",
      "remaining",
      "effort",
      "velocity",
      "sprint",
      "burndown",
      "chart",
      "project"
    ],
    "aliases": [],
    "description": "Burndown Chart — professional project and portfolio management icon for Power BI dashboards.",
    "recommendedUses": [
      "Project dashboards",
      "Sprint boards",
      "Milestone timelines"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 6 7 9 11 11 15 15 20 18\" fill=\"none\" stroke=\"#E03131\"/><path d=\"M4 6 8 10 12 12 16 16 20 18\" fill=\"none\" stroke=\"currentColor\" stroke-dasharray=\"3 2\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 6 7 9 11 11 15 15 20 18\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 6 8 10 12 12 16 16 20 18\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-product-roadmap",
    "name": "Product Roadmap",
    "primaryCategory": "product",
    "keywords": [
      "feature",
      "plan",
      "timeline",
      "quarter",
      "product",
      "roadmap"
    ],
    "aliases": [],
    "description": "Product Roadmap — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"3\" y=\"11\" width=\"18\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"3\" y=\"17\" width=\"18\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 5v4M14 11v4M11 17v4\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"3\" y=\"5\" width=\"5\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"3\" y=\"11\" width=\"8\" height=\"4\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"3\" y=\"17\" width=\"12\" height=\"4\" rx=\"1\" fill=\"#F08C00\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"5\" width=\"5\" height=\"4\" rx=\"1\" fill=\"#4C6EF5\"/><rect x=\"3\" y=\"11\" width=\"8\" height=\"4\" rx=\"1\" fill=\"#0CA678\"/><rect x=\"3\" y=\"17\" width=\"12\" height=\"4\" rx=\"1\" fill=\"#F08C00\"/><rect x=\"3\" y=\"5\" width=\"18\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"3\" y=\"11\" width=\"18\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><rect x=\"3\" y=\"17\" width=\"18\" height=\"4\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-feature-flag",
    "name": "Feature Flag",
    "primaryCategory": "product",
    "keywords": [
      "toggle",
      "rollout",
      "experiment",
      "enable",
      "feature",
      "flag",
      "product"
    ],
    "aliases": [],
    "description": "Feature Flag — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 8V5l3-1 3 1v3M14 8V6l2-1 2 1v2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"12\" r=\"2\" fill=\"#0CA678\"/><circle cx=\"16\" cy=\"12\" r=\"2\" fill=\"#868E96\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.12\"/><rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><circle cx=\"8\" cy=\"12\" r=\"2\" fill=\"#0CA678\"/><circle cx=\"16\" cy=\"12\" r=\"2\" fill=\"#868E96\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-user-story",
    "name": "User Story",
    "primaryCategory": "product",
    "keywords": [
      "agile",
      "backlog",
      "requirement",
      "persona",
      "user",
      "story",
      "product"
    ],
    "aliases": [],
    "description": "User Story — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"9\" cy=\"8\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"7\" width=\"7\" height=\"9\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 10h3M16 13h2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"9\" cy=\"8\" r=\"4\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M3 19a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"14\" y=\"7\" width=\"7\" height=\"9\" rx=\"1.5\" fill=\"#7048E8\" fill-opacity=\"0.12\"/><rect x=\"14\" y=\"7\" width=\"7\" height=\"9\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M16 10h3M16 13h2\" fill=\"none\" stroke=\"#7048E8\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-backlog",
    "name": "Product Backlog",
    "primaryCategory": "product",
    "keywords": [
      "item",
      "list",
      "priority",
      "queue",
      "agile",
      "backlog",
      "product"
    ],
    "aliases": [],
    "description": "Product Backlog — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 8h2M7 12h2M7 16h2M11 8h6M11 12h5M11 16h3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.06\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 8h2M7 12h2M7 16h2\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11 8h6M11 12h5M11 16h3\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-mvp",
    "name": "MVP",
    "primaryCategory": "product",
    "keywords": [
      "minimum",
      "viable",
      "product",
      "launch",
      "test",
      "mvp"
    ],
    "aliases": [],
    "description": "MVP — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5v1.5M3.5 12H5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.12\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 3.5v1.5M3.5 12H5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-release",
    "name": "Release",
    "primaryCategory": "product",
    "keywords": [
      "launch",
      "deploy",
      "version",
      "publish",
      "release",
      "product"
    ],
    "aliases": [],
    "description": "Release — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 20 7v5c0 3.5-3 6.5-8 8-5-1.5-8-4.5-8-8V7Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3 20 7v5c0 3.5-3 6.5-8 8-5-1.5-8-4.5-8-8V7Z\" fill=\"#0CA678\" fill-opacity=\"0.12\" stroke=\"none\"/><path d=\"M12 3 20 7v5c0 3.5-3 6.5-8 8-5-1.5-8-4.5-8-8V7Z\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-product-metrics",
    "name": "Product Metrics",
    "primaryCategory": "product",
    "keywords": [
      "dau",
      "mau",
      "engagement",
      "retention",
      "product",
      "metrics"
    ],
    "aliases": [],
    "description": "Product Metrics — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 17 9 13 12 15 16 9 20 11\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 17 9 13 12 15 16 9 20 11\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ux-research",
    "name": "UX Research",
    "primaryCategory": "product",
    "keywords": [
      "usability",
      "testing",
      "interview",
      "prototype",
      "ux",
      "research",
      "product"
    ],
    "aliases": [],
    "description": "UX Research — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"5\" width=\"7\" height=\"12\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 8h3M16 11h2M16 14h3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"14\" y=\"5\" width=\"7\" height=\"12\" rx=\"1.5\" fill=\"#1C7ED6\" fill-opacity=\"0.12\"/><rect x=\"14\" y=\"5\" width=\"7\" height=\"12\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M16 8h3M16 11h2M16 14h3\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-product-strategy",
    "name": "Product Strategy",
    "primaryCategory": "product",
    "keywords": [
      "vision",
      "positioning",
      "market",
      "fit",
      "product",
      "strategy"
    ],
    "aliases": [],
    "description": "Product Strategy — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 4 7v5c0 4 3.5 7.5 8 9 4.5-1.5 8-5 8-9V7Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 12l2 2 4-4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3 4 7v5c0 4 3.5 7.5 8 9 4.5-1.5 8-5 8-9V7Z\" fill=\"#4C6EF5\" fill-opacity=\"0.12\" stroke=\"none\"/><path d=\"M12 3 4 7v5c0 4 3.5 7.5 8 9 4.5-1.5 8-5 8-9V7Z\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 12l2 2 4-4\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-monetization",
    "name": "Monetization",
    "primaryCategory": "product",
    "keywords": [
      "revenue",
      "model",
      "pricing",
      "freemium",
      "monetization",
      "product"
    ],
    "aliases": [],
    "description": "Monetization — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"10\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5v1M12 15v1M12 16v4M9.5 19h5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9.5 8l2.5 2 2.5-2M9.5 12l2.5-2 2.5 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"10\" r=\"5\" fill=\"#F5A623\" fill-opacity=\"0.15\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M9.5 8l2.5 2 2.5-2M9.5 12l2.5-2 2.5 2\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 5v1M12 15v1M12 16v4M9.5 19h5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-adoption",
    "name": "Product Adoption",
    "primaryCategory": "product",
    "keywords": [
      "onboard",
      "active",
      "usage",
      "growth",
      "lifecycle",
      "adoption",
      "product"
    ],
    "aliases": [],
    "description": "Product Adoption — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 18 7 14 10 11 14 9 19 8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M19 8l-2 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4V20H20\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 18 7 14 10 11 14 9 19 8\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 8l-2 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-tech-debt",
    "name": "Tech Debt",
    "primaryCategory": "product",
    "keywords": [
      "legacy",
      "refactor",
      "code",
      "quality",
      "issue",
      "tech",
      "debt",
      "product"
    ],
    "aliases": [],
    "description": "Tech Debt — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 9l6 6M15 9l-6 6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5v1.5M20.5 12H19\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#E03131\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M9 9l6 6M15 9l-6 6\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 3.5v1.5M20.5 12H19\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-product-launch",
    "name": "Product Launch",
    "primaryCategory": "product",
    "keywords": [
      "go",
      "to",
      "market",
      "gtm",
      "release",
      "new",
      "product",
      "launch"
    ],
    "aliases": [
      "Growth Launch"
    ],
    "description": "Product Launch — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3l2 5h5l-4 3 1.5 5L12 13l-4.5 3L9 11 5 8h5Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3l2 5h5l-4 3 1.5 5L12 13l-4.5 3L9 11 5 8h5Z\" fill=\"#F5A623\" fill-opacity=\"0.2\" stroke=\"none\"/>",
    "multicolorSvg": "<path d=\"M12 3l2 5h5l-4 3 1.5 5L12 13l-4.5 3L9 11 5 8h5Z\" fill=\"#F5A623\" fill-opacity=\"0.25\" stroke=\"none\"/><path d=\"M12 3l2 5h5l-4 3 1.5 5L12 13l-4.5 3L9 11 5 8h5Z\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-api-design",
    "name": "API Design",
    "primaryCategory": "product",
    "keywords": [
      "interface",
      "contract",
      "endpoint",
      "developer",
      "api",
      "design",
      "product"
    ],
    "aliases": [],
    "description": "API Design — professional product management icon for Power BI dashboards.",
    "recommendedUses": [
      "Product dashboards",
      "Adoption funnels",
      "Release trackers"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 12h18\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 8V5l2-1 2 1v3M15 8V6l2-1 2 1v2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 16h3M12 16h5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\" fill=\"#1C7ED6\" fill-opacity=\"0.12\"/><rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M6 16h3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 16h5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
]
