// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const SALES_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-sales-funnel",
    "name": "Sales Funnel",
    "primaryCategory": "sales",
    "keywords": [
      "pipeline",
      "conversion",
      "marketing",
      "funnel",
      "sales"
    ],
    "aliases": [
      "Funnel Sales"
    ],
    "description": "Sales Funnel — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 4.5h17l-6 8v6.5l-5 2V12.5Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 4.5h17l-6 8v6.5l-5 2V12.5Z\" fill=\"#4C6EF5\" fill-opacity=\"0.2\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-customer",
    "name": "Customer",
    "primaryCategory": "sales",
    "keywords": [
      "client",
      "buyer",
      "person",
      "crm",
      "customer",
      "sales"
    ],
    "aliases": [],
    "description": "Customer — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"8\" r=\"3.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M5 20c0-3.6 3.1-6.5 7-6.5s7 2.9 7 6.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"8\" r=\"3.4\" fill=\"#4C6EF5\" fill-opacity=\"0.3\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M5 20c0-3.6 3.1-6.5 7-6.5s7 2.9 7 6.5\" fill=\"#4C6EF5\" fill-opacity=\"0.16\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-deal",
    "name": "Deal / Handshake",
    "primaryCategory": "sales",
    "keywords": [
      "agreement",
      "contract",
      "partnership",
      "sales",
      "deal",
      "handshake"
    ],
    "aliases": [
      "Handshake"
    ],
    "description": "Deal / Handshake — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M2.5 11.5 6 8l3 2 2-1.5 2 1.5 3-2 3.5 3.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6 13l3 3 2.5-2.5L14 16l3-3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M2.5 11.5 6 8l3 2 2-1.5 2 1.5 3-2 3.5 3.5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 13l3 3 2.5-2.5L14 16l3-3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-campaign",
    "name": "Campaign",
    "primaryCategory": "sales",
    "keywords": [
      "marketing",
      "promotion",
      "ad",
      "outreach",
      "campaign",
      "sales"
    ],
    "aliases": [],
    "description": "Campaign — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 10v4l5 1.2V8.8Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8.5 8.8 17 5.5v13l-8.5-3.3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6.5 15.2 7.5 19.5h2L8.5 15.2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M20.5 9.5v5\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 10v4l5 1.2V8.8Z\" fill=\"#F08C00\" fill-opacity=\"0.25\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M8.5 8.8 17 5.5v13l-8.5-3.3\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M6.5 15.2 7.5 19.5h2L8.5 15.2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M20.5 9.5v5\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-lead",
    "name": "Lead",
    "primaryCategory": "sales",
    "keywords": [
      "prospect",
      "contact",
      "crm",
      "pipeline",
      "lead",
      "sales"
    ],
    "aliases": [],
    "description": "Lead — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"9.5\" cy=\"9\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 19c0-3.3 2.7-5.8 6-5.8s6 2.5 6 5.8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16.5 7.5 19 10l3.5-4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"9.5\" cy=\"9\" r=\"3\" fill=\"#4C6EF5\" fill-opacity=\"0.25\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M3.5 19c0-3.3 2.7-5.8 6-5.8s6 2.5 6 5.8\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M16.5 7.5 19 10l3.5-4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.9000000000000001\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-conversion",
    "name": "Conversion Rate",
    "primaryCategory": "sales",
    "keywords": [
      "rate",
      "optimization",
      "marketing",
      "kpi",
      "conversion",
      "sales"
    ],
    "aliases": [],
    "description": "Conversion Rate — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 5.5h7l-2.5 6.5h7L8.5 19\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 5.5h7l-2.5 6.5h7L8.5 19\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-market-share",
    "name": "Market Share",
    "primaryCategory": "sales",
    "keywords": [
      "competitive",
      "analysis",
      "share",
      "marketing",
      "market",
      "sales"
    ],
    "aliases": [],
    "description": "Market Share — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 12 12 3.5A8.5 8.5 0 0 1 19.5 8Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\"/><path d=\"M12 12 12 3.5A8.5 8.5 0 0 1 19.5 8Z\" fill=\"#4C6EF5\" fill-opacity=\"0.4\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-megaphone",
    "name": "Promotion",
    "primaryCategory": "sales",
    "keywords": [
      "announcement",
      "marketing",
      "ad",
      "campaign",
      "megaphone",
      "promotion",
      "sales"
    ],
    "aliases": [],
    "description": "Promotion — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M3.5 10v4h3l9 4V6l-9 4Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M19.5 10.5a2.2 2.2 0 0 1 0 3\" stroke=\"currentColor\"/><path d=\"M6.5 14v3.5a1.3 1.3 0 0 0 1.3 1.3h.8\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M3.5 10v4h3l9 4V6l-9 4Z\" fill=\"#F08C00\" fill-opacity=\"0.25\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M19.5 10.5a2.2 2.2 0 0 1 0 3\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><path d=\"M6.5 14v3.5a1.3 1.3 0 0 0 1.3 1.3h.8\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-email-marketing",
    "name": "Email Campaign",
    "primaryCategory": "sales",
    "keywords": [
      "newsletter",
      "outreach",
      "send",
      "email",
      "marketing",
      "campaign",
      "sales"
    ],
    "aliases": [
      "Campaign Email"
    ],
    "description": "Email Campaign — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 8l9 6 9-6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M16 4l2 2 3-3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.1\"/><rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M3 8l9 6 9-6\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 4l2 2 3-3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-review-star",
    "name": "Customer Review",
    "primaryCategory": "sales",
    "keywords": [
      "rating",
      "feedback",
      "star",
      "testimonial",
      "review",
      "customer",
      "sales"
    ],
    "aliases": [],
    "description": "Customer Review — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 4l2.2 4.5 5 .7-3.6 3.5.9 5-4.5-2.4L7.5 20.7l.9-5L4.8 9.2l5-.7Z\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 4l2.2 4.5 5 .7-3.6 3.5.9 5-4.5-2.4L7.5 20.7l.9-5L4.8 9.2l5-.7Z\" fill=\"#F5A623\" stroke=\"#F5A623\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-discount",
    "name": "Discount",
    "primaryCategory": "sales",
    "keywords": [
      "sale",
      "offer",
      "percent",
      "tag",
      "discount",
      "sales"
    ],
    "aliases": [],
    "description": "Discount — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M4 4h7l9 9-7 7-9-9Z\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"8\" r=\"1.4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 15l4-4\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"11.2\" cy=\"11.2\" r=\"0.8\" fill=\"currentColor\"/><circle cx=\"14.8\" cy=\"14.8\" r=\"0.8\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M4 4h7l9 9-7 7-9-9Z\" fill=\"#E03131\" fill-opacity=\"0.12\"/><path d=\"M4 4h7l9 9-7 7-9-9Z\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"8\" cy=\"8\" r=\"1.4\" fill=\"#E03131\"/><path d=\"M11 15l4-4\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-loyalty",
    "name": "Loyalty Program",
    "primaryCategory": "sales",
    "keywords": [
      "rewards",
      "points",
      "member",
      "crown",
      "loyalty",
      "program",
      "sales"
    ],
    "aliases": [
      "Customer Loyalty"
    ],
    "description": "Loyalty Program — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M5 8l3 3 4-5 4 5 3-3-1.5 9H6.5Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M6.5 20h11\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"5\" cy=\"8\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"19\" cy=\"8\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"6\" r=\"0.9\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M5 8l3 3 4-5 4 5 3-3-1.5 9H6.5Z\" fill=\"#F5A623\" fill-opacity=\"0.2\"/><path d=\"M5 8l3 3 4-5 4 5 3-3-1.5 9H6.5Z\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6.5 20h11\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"6\" r=\"1\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-segment",
    "name": "Audience Segment",
    "primaryCategory": "sales",
    "keywords": [
      "group",
      "target",
      "market",
      "split",
      "segment",
      "audience",
      "sales"
    ],
    "aliases": [],
    "description": "Audience Segment — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"8\" cy=\"10\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"15\" cy=\"14\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M11 12a4 4 0 0 1 1 4 4 4 0 0 1-4-1\" fill=\"currentColor\" fill-opacity=\"0.15\" stroke=\"none\"/>",
    "multicolorSvg": "<circle cx=\"8\" cy=\"10\" r=\"4\" fill=\"#4C6EF5\" fill-opacity=\"0.18\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><circle cx=\"15\" cy=\"14\" r=\"4\" fill=\"#0CA678\" fill-opacity=\"0.18\" stroke=\"#0CA678\" stroke-width=\"1.6\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-pipeline",
    "name": "Sales Pipeline",
    "primaryCategory": "sales",
    "keywords": [
      "stages",
      "crm",
      "opportunity",
      "value",
      "pipeline",
      "sales"
    ],
    "aliases": [],
    "description": "Sales Pipeline — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"4\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"9.5\" y=\"8\" width=\"4\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"16\" y=\"8\" width=\"5\" height=\"8\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 12h2.5M13.5 12h2.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"8\" width=\"4\" height=\"8\" rx=\"2\" fill=\"#4C6EF5\"/><rect x=\"9.5\" y=\"8\" width=\"4\" height=\"8\" rx=\"2\" fill=\"#F08C00\"/><rect x=\"16\" y=\"8\" width=\"5\" height=\"8\" rx=\"2\" fill=\"#0CA678\"/><path d=\"M7 12h2.5M13.5 12h2.5\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-win-rate",
    "name": "Win Rate",
    "primaryCategory": "sales",
    "keywords": [
      "close",
      "ratio",
      "quota",
      "success",
      "percent",
      "win",
      "rate",
      "sales"
    ],
    "aliases": [],
    "description": "Win Rate — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 3.5v-1.5M20.5 12H22M12 20.5V22M3.5 12H2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-quota",
    "name": "Sales Quota",
    "primaryCategory": "sales",
    "keywords": [
      "target",
      "achieved",
      "monthly",
      "rep",
      "quota",
      "sales"
    ],
    "aliases": [],
    "description": "Sales Quota — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 12H20V20H4Z\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"none\"/><path d=\"M12 4V12\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 4V12M12 12v8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9l4-5 4 5\" fill=\"none\" stroke=\"#4C6EF5\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#868E96\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M4 12H20V20H4Z\" fill=\"#0CA678\" fill-opacity=\"0.3\" stroke=\"none\"/><path d=\"M8 9l4-5 4 5\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-churn",
    "name": "Customer Churn",
    "primaryCategory": "sales",
    "keywords": [
      "attrition",
      "loss",
      "retention",
      "cancel",
      "churn",
      "customer",
      "sales"
    ],
    "aliases": [],
    "description": "Customer Churn — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 7l4 4M21 7l-4 4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"#868E96\" fill-opacity=\"0.15\" stroke=\"#868E96\" stroke-width=\"1.6\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 7l4 4M21 7l-4 4\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-retention",
    "name": "Customer Retention",
    "primaryCategory": "sales",
    "keywords": [
      "loyal",
      "keep",
      "upsell",
      "renew",
      "retention",
      "customer",
      "sales"
    ],
    "aliases": [],
    "description": "Customer Retention — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 8l2 2 3-3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 8l2 2 3-3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-upsell",
    "name": "Upsell",
    "primaryCategory": "sales",
    "keywords": [
      "cross-sell",
      "expand",
      "revenue",
      "tier",
      "upsell",
      "sales"
    ],
    "aliases": [],
    "description": "Upsell — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M17 16V9M14 11l3-3 3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"10\" cy=\"9\" r=\"4\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M4 20a6 6 0 0 1 12 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 16V9M14 11l3-3 3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-clv",
    "name": "Customer Lifetime Value",
    "primaryCategory": "sales",
    "keywords": [
      "ltv",
      "value",
      "revenue",
      "loyal",
      "clv",
      "customer",
      "lifetime",
      "sales"
    ],
    "aliases": [],
    "description": "Customer Lifetime Value — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"11\" r=\"6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5V3M12 17v4M9 21h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9.5 9l2.5 2 2.5-2\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"11\" r=\"1.1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"11\" r=\"6\" fill=\"#F5A623\" fill-opacity=\"0.15\" stroke=\"#F5A623\" stroke-width=\"1.6\"/><path d=\"M12 5V3M12 17v4M9 21h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9.5 9l2.5 2 2.5-2\" fill=\"none\" stroke=\"#F5A623\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-nps",
    "name": "NPS Score",
    "primaryCategory": "sales",
    "keywords": [
      "net",
      "promoter",
      "satisfaction",
      "survey",
      "nps",
      "score",
      "sales"
    ],
    "aliases": [],
    "description": "NPS Score — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 14a4 4 0 0 1 8 0\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"9\" cy=\"10\" r=\"1\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"10\" r=\"1\" fill=\"currentColor\"/><path d=\"M12 3.5v1.5M3.5 12H5M19 12h1.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"#0CA678\" fill-opacity=\"0.1\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M8 14a4 4 0 0 1 8 0\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"9\" cy=\"10\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"15\" cy=\"10\" r=\"1.2\" fill=\"#4C6EF5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-territory",
    "name": "Sales Territory",
    "primaryCategory": "sales",
    "keywords": [
      "region",
      "zone",
      "map",
      "coverage",
      "territory",
      "sales"
    ],
    "aliases": [],
    "description": "Sales Territory — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 10h16M4 16h16M10 4v16\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"7\" cy=\"7\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"7\" r=\"1.2\" fill=\"#0CA678\"/><circle cx=\"7\" cy=\"13\" r=\"1.2\" fill=\"#F08C00\"/><circle cx=\"14\" cy=\"13\" r=\"1.2\" fill=\"#4C6EF5\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"#1C7ED6\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M4 10h16M4 16h16M10 4v16\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"7\" cy=\"7\" r=\"1.3\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"7\" r=\"1.3\" fill=\"#0CA678\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ab-test",
    "name": "A/B Test",
    "primaryCategory": "sales",
    "keywords": [
      "experiment",
      "variant",
      "optimize",
      "ab",
      "test",
      "sales"
    ],
    "aliases": [],
    "description": "A/B Test — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 12h4\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4.5 11h4M4.5 13.5h2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15 11h4M15 13.5h2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"14\" y=\"8\" width=\"7\" height=\"8\" rx=\"1.5\" fill=\"#0CA678\" fill-opacity=\"0.85\"/><path d=\"M10 12h4\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-social-media",
    "name": "Social Media",
    "primaryCategory": "sales",
    "keywords": [
      "linkedin",
      "post",
      "share",
      "engagement",
      "social",
      "media",
      "sales"
    ],
    "aliases": [],
    "description": "Social Media — professional sales and marketing icon for Power BI dashboards.",
    "recommendedUses": [
      "Sales dashboards",
      "Funnel reports",
      "Campaign scorecards"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12h8M12 8v8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15.5 8.5l1.5-1.5M7 17l1.5-1.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#1C7ED6\" fill-opacity=\"0.12\" stroke=\"#1C7ED6\" stroke-width=\"1.6\"/><path d=\"M8 12h8M12 8v8\" fill=\"none\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-customer-journey",
    "name": "Customer Journey",
    "primaryCategory": "cx",
    "keywords": [
      "touchpoint",
      "map",
      "experience",
      "path",
      "customer",
      "journey",
      "cx"
    ],
    "aliases": [],
    "description": "Customer Journey — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"4\" cy=\"12\" r=\"1.3\" fill=\"#4C6EF5\"/><circle cx=\"9\" cy=\"8\" r=\"1.3\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"12\" r=\"1.3\" fill=\"#0CA678\"/><circle cx=\"19\" cy=\"8\" r=\"1.3\" fill=\"#0CA678\"/><path d=\"M4 12 9 8 14 12 19 8\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 14v2M9 10v2M14 14v2M19 10v2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"4\" cy=\"12\" r=\"1.4\" fill=\"#4C6EF5\"/><circle cx=\"9\" cy=\"8\" r=\"1.4\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"12\" r=\"1.4\" fill=\"#0CA678\"/><circle cx=\"19\" cy=\"8\" r=\"1.4\" fill=\"#0CA678\"/><path d=\"M4 12 9 8 14 12 19 8\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-ticket",
    "name": "Support Ticket",
    "primaryCategory": "cx",
    "keywords": [
      "issue",
      "request",
      "help",
      "desk",
      "case",
      "ticket",
      "support",
      "cx"
    ],
    "aliases": [],
    "description": "Support Ticket — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 10H20\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 14h10M7 17h6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 7.5h6\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"5\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.85\"/><rect x=\"4\" y=\"5\" width=\"16\" height=\"14\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M7 14h10M7 17h6\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-first-response",
    "name": "First Response Time",
    "primaryCategory": "cx",
    "keywords": [
      "frt",
      "sla",
      "speed",
      "reply",
      "fast",
      "first",
      "response",
      "time",
      "cx"
    ],
    "aliases": [],
    "description": "First Response Time — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7v5l3 2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 12H1M23 12h-2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 5l1 1M17 5l-1 1\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#1C7ED6\" fill-opacity=\"0.1\" stroke=\"#1C7ED6\" stroke-width=\"1.6\"/><path d=\"M12 7v5l3 2\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M3 12H1M23 12h-2\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-escalation",
    "name": "Escalation",
    "primaryCategory": "cx",
    "keywords": [
      "priority",
      "urgent",
      "raise",
      "level",
      "critical",
      "escalation",
      "cx"
    ],
    "aliases": [],
    "description": "Escalation — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3 4 7v5c0 4.5 3.5 8 8 9 4.5-1 8-4.5 8-9V7Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 9v4\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"16\" r=\"1.2\" fill=\"#E03131\"/>",
    "multicolorSvg": "<path d=\"M12 3 4 7v5c0 4.5 3.5 8 8 9 4.5-1 8-4.5 8-9V7Z\" fill=\"#E03131\" fill-opacity=\"0.15\" stroke=\"none\"/><path d=\"M12 3 4 7v5c0 4.5 3.5 8 8 9 4.5-1 8-4.5 8-9V7Z\" fill=\"none\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 9v4\" fill=\"none\" stroke=\"#fff\" stroke-width=\"1.9\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"12\" cy=\"16\" r=\"1.3\" fill=\"#fff\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-resolution",
    "name": "Issue Resolution",
    "primaryCategory": "cx",
    "keywords": [
      "solved",
      "close",
      "fix",
      "done",
      "complete",
      "resolution",
      "issue",
      "cx"
    ],
    "aliases": [],
    "description": "Issue Resolution — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.15\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M8 12l2.5 2.5L16 9\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-csat",
    "name": "CSAT",
    "primaryCategory": "cx",
    "keywords": [
      "satisfaction",
      "score",
      "happy",
      "customer",
      "survey",
      "csat",
      "cx"
    ],
    "aliases": [
      "Customer Satisfaction"
    ],
    "description": "CSAT — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"11\" r=\"7\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 14a3 3 0 0 0 6 0\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"10\" cy=\"9.5\" r=\"1\" fill=\"currentColor\"/><circle cx=\"14\" cy=\"9.5\" r=\"1\" fill=\"currentColor\"/><path d=\"M12 4v1.5M12 18v4M8 22h8\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"11\" r=\"7\" fill=\"#0CA678\" fill-opacity=\"0.12\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M9 14a3 3 0 0 0 6 0\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"10\" cy=\"9.5\" r=\"1.2\" fill=\"#4C6EF5\"/><circle cx=\"14\" cy=\"9.5\" r=\"1.2\" fill=\"#4C6EF5\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-voice-of-customer",
    "name": "Voice of Customer",
    "primaryCategory": "cx",
    "keywords": [
      "voc",
      "feedback",
      "listen",
      "insight",
      "voice",
      "of",
      "customer",
      "cx"
    ],
    "aliases": [],
    "description": "Voice of Customer — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 15l-2 4 4-2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M7 9h10M7 12h7\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M18 4l2 2-2 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"5\" width=\"16\" height=\"10\" rx=\"2\" fill=\"#4C6EF5\" fill-opacity=\"0.1\"/><rect x=\"4\" y=\"5\" width=\"16\" height=\"10\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 15l-2 4 4-2\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 9h10M7 12h7\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 4l2 2-2 2\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-persona",
    "name": "Customer Persona",
    "primaryCategory": "cx",
    "keywords": [
      "profile",
      "archetype",
      "segment",
      "user",
      "persona",
      "customer",
      "cx"
    ],
    "aliases": [],
    "description": "Customer Persona — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"8\" r=\"5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M4 20a8 8 0 0 1 16 0\" fill=\"none\" stroke=\"currentColor\"/><rect x=\"14\" y=\"4\" width=\"5\" height=\"5\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M15 5v3M16.5 5v3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"8\" r=\"5\" fill=\"#4C6EF5\" fill-opacity=\"0.15\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M4 20a8 8 0 0 1 16 0\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"14\" y=\"4\" width=\"5\" height=\"5\" rx=\"2\" fill=\"#0CA678\" fill-opacity=\"0.8\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-chat-support",
    "name": "Live Chat",
    "primaryCategory": "cx",
    "keywords": [
      "messaging",
      "instant",
      "help",
      "widget",
      "chat",
      "support",
      "live",
      "cx"
    ],
    "aliases": [
      "Headset"
    ],
    "description": "Live Chat — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3 8l9 6 9-6\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 16l-4 4v-4\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\" fill=\"#0CA678\" fill-opacity=\"0.12\"/><rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M3 8l9 6 9-6\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9 16l-4 4v-4\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-knowledge-base",
    "name": "Knowledge Base",
    "primaryCategory": "cx",
    "keywords": [
      "faq",
      "self-service",
      "article",
      "help",
      "knowledge",
      "base",
      "cx"
    ],
    "aliases": [],
    "description": "Knowledge Base — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 9h8M8 12h8M8 15h5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"16\" cy=\"16\" r=\"3\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M14.5 14.5l.7.7L17 13.5\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"#1C7ED6\" fill-opacity=\"0.08\"/><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"/><path d=\"M8 9h8M8 12h8\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"16\" cy=\"16\" r=\"3\" fill=\"#0CA678\" fill-opacity=\"0.2\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M14.5 14.5l.7.7L17 13.5\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-feedback-loop",
    "name": "Feedback Loop",
    "primaryCategory": "cx",
    "keywords": [
      "improve",
      "iterate",
      "listen",
      "act",
      "feedback",
      "loop",
      "cx"
    ],
    "aliases": [],
    "description": "Feedback Loop — professional customer experience and support icon for Power BI dashboards.",
    "recommendedUses": [
      "CX dashboards",
      "NPS/CSAT cards",
      "Support queue reports"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"7\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5v2M12 17v2M5 12H7M17 12h2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 19a7 7 0 0 1 0-14\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 5l3 3-3 3\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"7\" fill=\"#4C6EF5\" fill-opacity=\"0.1\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 19a7 7 0 0 1 0-14\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 5l3 3-3 3\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 12H7M17 12h2\" fill=\"none\" stroke=\"#868E96\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
]
