// GENERATED by scripts/generate-icon-library.mjs — do not edit by hand.
// Source geometry adapted from docs/reference/icon-library/ (curated + deduplicated).
import type { IconConcept } from '@/lib/icon-library/types'

export const STATUS_CONCEPTS: IconConcept[] = [
  {
    "id": "v2-status-success",
    "name": "Status: Success",
    "primaryCategory": "status",
    "keywords": [
      "complete",
      "done",
      "ok",
      "success",
      "status"
    ],
    "aliases": [],
    "description": "Status: Success — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M8 12.3 10.6 15 16 9\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#0CA678\" fill-opacity=\"0.18\" stroke=\"#0CA678\" stroke-width=\"1.6\"/><path d=\"M8 12.3 10.6 15 16 9\" fill=\"none\" stroke=\"#0CA678\" stroke-width=\"2.0\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-status-failure",
    "name": "Status: Failure",
    "primaryCategory": "status",
    "keywords": [
      "error",
      "fail",
      "rejected",
      "status",
      "failure"
    ],
    "aliases": [],
    "description": "Status: Failure — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M9 9l6 6M15 9l-6 6\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#E03131\" fill-opacity=\"0.16\" stroke=\"#E03131\" stroke-width=\"1.6\"/><path d=\"M9 9l6 6M15 9l-6 6\" stroke=\"#E03131\" stroke-width=\"2.0\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-status-pending",
    "name": "Status: Pending",
    "primaryCategory": "status",
    "keywords": [
      "waiting",
      "in",
      "progress",
      "pending",
      "status"
    ],
    "aliases": [],
    "description": "Status: Pending — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7.5V12l3 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#F08C00\" fill-opacity=\"0.16\" stroke=\"#F08C00\" stroke-width=\"1.6\"/><path d=\"M12 7.5V12l3 2\" fill=\"none\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-status-warning",
    "name": "Status: Warning",
    "primaryCategory": "status",
    "keywords": [
      "caution",
      "alert",
      "warning",
      "status"
    ],
    "aliases": [],
    "description": "Status: Warning — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M12 3.5 21 19.5H3Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 9.5v4.5\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"16.7\" r=\"1\" fill=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M12 3.5 21 19.5H3Z\" fill=\"#F08C00\" fill-opacity=\"0.2\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M12 9.5v4.5\" stroke=\"#F08C00\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><circle cx=\"12\" cy=\"16.7\" r=\"1.1\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-notification",
    "name": "Notification / Alert",
    "primaryCategory": "status",
    "keywords": [
      "bell",
      "alert",
      "notification",
      "status"
    ],
    "aliases": [
      "Notification"
    ],
    "description": "Notification / Alert — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<path d=\"M6 10a6 6 0 0 1 12 0c0 4 1.5 5.5 1.5 5.5h-15S6 14 6 10Z\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M10 18.5a2 2 0 0 0 4 0\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<path d=\"M6 10a6 6 0 0 1 12 0c0 4 1.5 5.5 1.5 5.5h-15S6 14 6 10Z\" fill=\"#E03131\" fill-opacity=\"0.16\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M10 18.5a2 2 0 0 0 4 0\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><circle cx=\"17.5\" cy=\"6\" r=\"2.2\" fill=\"#E03131\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-info",
    "name": "Information",
    "primaryCategory": "status",
    "keywords": [
      "details",
      "help",
      "info",
      "status",
      "information"
    ],
    "aliases": [],
    "description": "Information — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><circle cx=\"12\" cy=\"8\" r=\"1\" fill=\"currentColor\"/><path d=\"M12 11.5V17\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#1C7ED6\" fill-opacity=\"0.16\" stroke=\"#1C7ED6\" stroke-width=\"1.6\"/><circle cx=\"12\" cy=\"8\" r=\"1.1\" fill=\"#1C7ED6\"/><path d=\"M12 11.5V17\" stroke=\"#1C7ED6\" stroke-width=\"1.6\" stroke-linecap=\"round\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-calendar",
    "name": "Calendar / Date",
    "primaryCategory": "status",
    "keywords": [
      "date",
      "schedule",
      "time",
      "calendar",
      "status"
    ],
    "aliases": [
      "Calendar"
    ],
    "description": "Calendar / Date — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15.5\" rx=\"2\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M3.5 9.5h17\" stroke=\"currentColor\"/><path d=\"M8 3v4M16 3v4\" stroke=\"currentColor\"/><circle cx=\"8\" cy=\"13.5\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"12\" cy=\"13.5\" r=\"0.9\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"13.5\" r=\"0.9\" fill=\"currentColor\"/>",
    "multicolorSvg": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15.5\" rx=\"2\" fill=\"none\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M3.5 9.5h17\" stroke=\"#2B2D42\" stroke-width=\"1.6\"/><path d=\"M8 3v4M16 3v4\" stroke=\"#E03131\" stroke-width=\"1.6\" stroke-linecap=\"round\"/><circle cx=\"8\" cy=\"13.5\" r=\"1\" fill=\"#4C6EF5\"/><circle cx=\"12\" cy=\"13.5\" r=\"1\" fill=\"#0CA678\"/><circle cx=\"16\" cy=\"13.5\" r=\"1\" fill=\"#F08C00\"/>",
    "source": "bi-icon-studio"
  },
  {
    "id": "v2-time-clock",
    "name": "Time / Duration",
    "primaryCategory": "status",
    "keywords": [
      "clock",
      "duration",
      "time",
      "status"
    ],
    "aliases": [
      "Time Tracked"
    ],
    "description": "Time / Duration — professional status and alerting icon for Power BI dashboards.",
    "recommendedUses": [
      "Status indicators",
      "Conditional formatting icons",
      "Alert banners"
    ],
    "viewBox": "0 0 24 24",
    "monochromeSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"none\" stroke=\"currentColor\"/><path d=\"M12 7.5V12l3.5 2\" fill=\"none\" stroke=\"currentColor\"/>",
    "multicolorSvg": "<circle cx=\"12\" cy=\"12\" r=\"8.5\" fill=\"#4C6EF5\" fill-opacity=\"0.14\" stroke=\"#4C6EF5\" stroke-width=\"1.6\"/><path d=\"M12 7.5V12l3.5 2\" fill=\"none\" stroke=\"#4C6EF5\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>",
    "source": "bi-icon-studio"
  },
]
